// source: proto/r4/core/resources/device_use_statement.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
var proto_annotations_pb = require('../../../../proto/annotations_pb.js');
goog.object.extend(proto, proto_annotations_pb);
var proto_r4_core_codes_pb = require('../../../../proto/r4/core/codes_pb.js');
goog.object.extend(proto, proto_r4_core_codes_pb);
var proto_r4_core_datatypes_pb = require('../../../../proto/r4/core/datatypes_pb.js');
goog.object.extend(proto, proto_r4_core_datatypes_pb);
goog.exportSymbol('proto.google.fhir.r4.core.DeviceUseStatement', null, global);
goog.exportSymbol('proto.google.fhir.r4.core.DeviceUseStatement.StatusCode', null, global);
goog.exportSymbol('proto.google.fhir.r4.core.DeviceUseStatement.TimingX', null, global);
goog.exportSymbol('proto.google.fhir.r4.core.DeviceUseStatement.TimingX.ChoiceCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.fhir.r4.core.DeviceUseStatement = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.fhir.r4.core.DeviceUseStatement.repeatedFields_, null);
};
goog.inherits(proto.google.fhir.r4.core.DeviceUseStatement, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.fhir.r4.core.DeviceUseStatement.displayName = 'proto.google.fhir.r4.core.DeviceUseStatement';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.fhir.r4.core.DeviceUseStatement.StatusCode = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.repeatedFields_, null);
};
goog.inherits(proto.google.fhir.r4.core.DeviceUseStatement.StatusCode, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.displayName = 'proto.google.fhir.r4.core.DeviceUseStatement.StatusCode';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.google.fhir.r4.core.DeviceUseStatement.TimingX.oneofGroups_);
};
goog.inherits(proto.google.fhir.r4.core.DeviceUseStatement.TimingX, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.fhir.r4.core.DeviceUseStatement.TimingX.displayName = 'proto.google.fhir.r4.core.DeviceUseStatement.TimingX';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.fhir.r4.core.DeviceUseStatement.repeatedFields_ = [6,8,9,10,11,14,19,20,22];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.toObject = function(opt_includeInstance) {
  return proto.google.fhir.r4.core.DeviceUseStatement.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.fhir.r4.core.DeviceUseStatement} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.DeviceUseStatement.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && proto_r4_core_datatypes_pb.Id.toObject(includeInstance, f),
    meta: (f = msg.getMeta()) && proto_r4_core_datatypes_pb.Meta.toObject(includeInstance, f),
    implicitRules: (f = msg.getImplicitRules()) && proto_r4_core_datatypes_pb.Uri.toObject(includeInstance, f),
    language: (f = msg.getLanguage()) && proto_r4_core_datatypes_pb.Code.toObject(includeInstance, f),
    text: (f = msg.getText()) && proto_r4_core_datatypes_pb.Narrative.toObject(includeInstance, f),
    containedList: jspb.Message.toObjectList(msg.getContainedList(),
    google_protobuf_any_pb.Any.toObject, includeInstance),
    extensionList: jspb.Message.toObjectList(msg.getExtensionList(),
    proto_r4_core_datatypes_pb.Extension.toObject, includeInstance),
    modifierExtensionList: jspb.Message.toObjectList(msg.getModifierExtensionList(),
    proto_r4_core_datatypes_pb.Extension.toObject, includeInstance),
    identifierList: jspb.Message.toObjectList(msg.getIdentifierList(),
    proto_r4_core_datatypes_pb.Identifier.toObject, includeInstance),
    basedOnList: jspb.Message.toObjectList(msg.getBasedOnList(),
    proto_r4_core_datatypes_pb.Reference.toObject, includeInstance),
    status: (f = msg.getStatus()) && proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.toObject(includeInstance, f),
    subject: (f = msg.getSubject()) && proto_r4_core_datatypes_pb.Reference.toObject(includeInstance, f),
    derivedFromList: jspb.Message.toObjectList(msg.getDerivedFromList(),
    proto_r4_core_datatypes_pb.Reference.toObject, includeInstance),
    timing: (f = msg.getTiming()) && proto.google.fhir.r4.core.DeviceUseStatement.TimingX.toObject(includeInstance, f),
    recordedOn: (f = msg.getRecordedOn()) && proto_r4_core_datatypes_pb.DateTime.toObject(includeInstance, f),
    source: (f = msg.getSource()) && proto_r4_core_datatypes_pb.Reference.toObject(includeInstance, f),
    device: (f = msg.getDevice()) && proto_r4_core_datatypes_pb.Reference.toObject(includeInstance, f),
    reasonCodeList: jspb.Message.toObjectList(msg.getReasonCodeList(),
    proto_r4_core_datatypes_pb.CodeableConcept.toObject, includeInstance),
    reasonReferenceList: jspb.Message.toObjectList(msg.getReasonReferenceList(),
    proto_r4_core_datatypes_pb.Reference.toObject, includeInstance),
    bodySite: (f = msg.getBodySite()) && proto_r4_core_datatypes_pb.CodeableConcept.toObject(includeInstance, f),
    noteList: jspb.Message.toObjectList(msg.getNoteList(),
    proto_r4_core_datatypes_pb.Annotation.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement}
 */
proto.google.fhir.r4.core.DeviceUseStatement.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.fhir.r4.core.DeviceUseStatement;
  return proto.google.fhir.r4.core.DeviceUseStatement.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.fhir.r4.core.DeviceUseStatement} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement}
 */
proto.google.fhir.r4.core.DeviceUseStatement.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto_r4_core_datatypes_pb.Id;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Id.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = new proto_r4_core_datatypes_pb.Meta;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Meta.deserializeBinaryFromReader);
      msg.setMeta(value);
      break;
    case 3:
      var value = new proto_r4_core_datatypes_pb.Uri;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Uri.deserializeBinaryFromReader);
      msg.setImplicitRules(value);
      break;
    case 4:
      var value = new proto_r4_core_datatypes_pb.Code;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Code.deserializeBinaryFromReader);
      msg.setLanguage(value);
      break;
    case 5:
      var value = new proto_r4_core_datatypes_pb.Narrative;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Narrative.deserializeBinaryFromReader);
      msg.setText(value);
      break;
    case 6:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.addContained(value);
      break;
    case 8:
      var value = new proto_r4_core_datatypes_pb.Extension;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Extension.deserializeBinaryFromReader);
      msg.addExtension$(value);
      break;
    case 9:
      var value = new proto_r4_core_datatypes_pb.Extension;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Extension.deserializeBinaryFromReader);
      msg.addModifierExtension(value);
      break;
    case 10:
      var value = new proto_r4_core_datatypes_pb.Identifier;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Identifier.deserializeBinaryFromReader);
      msg.addIdentifier(value);
      break;
    case 11:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.addBasedOn(value);
      break;
    case 12:
      var value = new proto.google.fhir.r4.core.DeviceUseStatement.StatusCode;
      reader.readMessage(value,proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 13:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.setSubject(value);
      break;
    case 14:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.addDerivedFrom(value);
      break;
    case 15:
      var value = new proto.google.fhir.r4.core.DeviceUseStatement.TimingX;
      reader.readMessage(value,proto.google.fhir.r4.core.DeviceUseStatement.TimingX.deserializeBinaryFromReader);
      msg.setTiming(value);
      break;
    case 16:
      var value = new proto_r4_core_datatypes_pb.DateTime;
      reader.readMessage(value,proto_r4_core_datatypes_pb.DateTime.deserializeBinaryFromReader);
      msg.setRecordedOn(value);
      break;
    case 17:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.setSource(value);
      break;
    case 18:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.setDevice(value);
      break;
    case 19:
      var value = new proto_r4_core_datatypes_pb.CodeableConcept;
      reader.readMessage(value,proto_r4_core_datatypes_pb.CodeableConcept.deserializeBinaryFromReader);
      msg.addReasonCode(value);
      break;
    case 20:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.addReasonReference(value);
      break;
    case 21:
      var value = new proto_r4_core_datatypes_pb.CodeableConcept;
      reader.readMessage(value,proto_r4_core_datatypes_pb.CodeableConcept.deserializeBinaryFromReader);
      msg.setBodySite(value);
      break;
    case 22:
      var value = new proto_r4_core_datatypes_pb.Annotation;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Annotation.deserializeBinaryFromReader);
      msg.addNote(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.fhir.r4.core.DeviceUseStatement.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.fhir.r4.core.DeviceUseStatement} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.DeviceUseStatement.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto_r4_core_datatypes_pb.Id.serializeBinaryToWriter
    );
  }
  f = message.getMeta();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto_r4_core_datatypes_pb.Meta.serializeBinaryToWriter
    );
  }
  f = message.getImplicitRules();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto_r4_core_datatypes_pb.Uri.serializeBinaryToWriter
    );
  }
  f = message.getLanguage();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto_r4_core_datatypes_pb.Code.serializeBinaryToWriter
    );
  }
  f = message.getText();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto_r4_core_datatypes_pb.Narrative.serializeBinaryToWriter
    );
  }
  f = message.getContainedList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
  f = message.getExtensionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      proto_r4_core_datatypes_pb.Extension.serializeBinaryToWriter
    );
  }
  f = message.getModifierExtensionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      proto_r4_core_datatypes_pb.Extension.serializeBinaryToWriter
    );
  }
  f = message.getIdentifierList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      proto_r4_core_datatypes_pb.Identifier.serializeBinaryToWriter
    );
  }
  f = message.getBasedOnList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.serializeBinaryToWriter
    );
  }
  f = message.getSubject();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getDerivedFromList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      14,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getTiming();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      proto.google.fhir.r4.core.DeviceUseStatement.TimingX.serializeBinaryToWriter
    );
  }
  f = message.getRecordedOn();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      proto_r4_core_datatypes_pb.DateTime.serializeBinaryToWriter
    );
  }
  f = message.getSource();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getDevice();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getReasonCodeList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      19,
      f,
      proto_r4_core_datatypes_pb.CodeableConcept.serializeBinaryToWriter
    );
  }
  f = message.getReasonReferenceList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      20,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getBodySite();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      proto_r4_core_datatypes_pb.CodeableConcept.serializeBinaryToWriter
    );
  }
  f = message.getNoteList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      22,
      f,
      proto_r4_core_datatypes_pb.Annotation.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.prototype.toObject = function(opt_includeInstance) {
  return proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.fhir.r4.core.DeviceUseStatement.StatusCode} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: jspb.Message.getFieldWithDefault(msg, 1, 0),
    id: (f = msg.getId()) && proto_r4_core_datatypes_pb.String.toObject(includeInstance, f),
    extensionList: jspb.Message.toObjectList(msg.getExtensionList(),
    proto_r4_core_datatypes_pb.Extension.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement.StatusCode}
 */
proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.fhir.r4.core.DeviceUseStatement.StatusCode;
  return proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.fhir.r4.core.DeviceUseStatement.StatusCode} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement.StatusCode}
 */
proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.google.fhir.r4.core.DeviceUseStatementStatusCode.Value} */ (reader.readEnum());
      msg.setValue(value);
      break;
    case 2:
      var value = new proto_r4_core_datatypes_pb.String;
      reader.readMessage(value,proto_r4_core_datatypes_pb.String.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 3:
      var value = new proto_r4_core_datatypes_pb.Extension;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Extension.deserializeBinaryFromReader);
      msg.addExtension$(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.fhir.r4.core.DeviceUseStatement.StatusCode} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValue();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto_r4_core_datatypes_pb.String.serializeBinaryToWriter
    );
  }
  f = message.getExtensionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto_r4_core_datatypes_pb.Extension.serializeBinaryToWriter
    );
  }
};


/**
 * optional DeviceUseStatementStatusCode.Value value = 1;
 * @return {!proto.google.fhir.r4.core.DeviceUseStatementStatusCode.Value}
 */
proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.prototype.getValue = function() {
  return /** @type {!proto.google.fhir.r4.core.DeviceUseStatementStatusCode.Value} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.google.fhir.r4.core.DeviceUseStatementStatusCode.Value} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement.StatusCode} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.prototype.setValue = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional String id = 2;
 * @return {?proto.google.fhir.r4.core.String}
 */
proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.prototype.getId = function() {
  return /** @type{?proto.google.fhir.r4.core.String} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.String, 2));
};


/**
 * @param {?proto.google.fhir.r4.core.String|undefined} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement.StatusCode} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement.StatusCode} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.prototype.hasId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated Extension extension = 3;
 * @return {!Array<!proto.google.fhir.r4.core.Extension>}
 */
proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.prototype.getExtensionList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Extension>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Extension, 3));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Extension>} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement.StatusCode} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.prototype.setExtensionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Extension=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Extension}
 */
proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.prototype.addExtension$ = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.google.fhir.r4.core.Extension, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement.StatusCode} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.StatusCode.prototype.clearExtensionList = function() {
  return this.setExtensionList([]);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.ChoiceCase = {
  CHOICE_NOT_SET: 0,
  TIMING: 1,
  PERIOD: 2,
  DATE_TIME: 3
};

/**
 * @return {proto.google.fhir.r4.core.DeviceUseStatement.TimingX.ChoiceCase}
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.prototype.getChoiceCase = function() {
  return /** @type {proto.google.fhir.r4.core.DeviceUseStatement.TimingX.ChoiceCase} */(jspb.Message.computeOneofCase(this, proto.google.fhir.r4.core.DeviceUseStatement.TimingX.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.prototype.toObject = function(opt_includeInstance) {
  return proto.google.fhir.r4.core.DeviceUseStatement.TimingX.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.fhir.r4.core.DeviceUseStatement.TimingX} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.toObject = function(includeInstance, msg) {
  var f, obj = {
    timing: (f = msg.getTiming()) && proto_r4_core_datatypes_pb.Timing.toObject(includeInstance, f),
    period: (f = msg.getPeriod()) && proto_r4_core_datatypes_pb.Period.toObject(includeInstance, f),
    dateTime: (f = msg.getDateTime()) && proto_r4_core_datatypes_pb.DateTime.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement.TimingX}
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.fhir.r4.core.DeviceUseStatement.TimingX;
  return proto.google.fhir.r4.core.DeviceUseStatement.TimingX.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.fhir.r4.core.DeviceUseStatement.TimingX} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement.TimingX}
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto_r4_core_datatypes_pb.Timing;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Timing.deserializeBinaryFromReader);
      msg.setTiming(value);
      break;
    case 2:
      var value = new proto_r4_core_datatypes_pb.Period;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Period.deserializeBinaryFromReader);
      msg.setPeriod(value);
      break;
    case 3:
      var value = new proto_r4_core_datatypes_pb.DateTime;
      reader.readMessage(value,proto_r4_core_datatypes_pb.DateTime.deserializeBinaryFromReader);
      msg.setDateTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.fhir.r4.core.DeviceUseStatement.TimingX.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.fhir.r4.core.DeviceUseStatement.TimingX} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTiming();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto_r4_core_datatypes_pb.Timing.serializeBinaryToWriter
    );
  }
  f = message.getPeriod();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto_r4_core_datatypes_pb.Period.serializeBinaryToWriter
    );
  }
  f = message.getDateTime();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto_r4_core_datatypes_pb.DateTime.serializeBinaryToWriter
    );
  }
};


/**
 * optional Timing timing = 1;
 * @return {?proto.google.fhir.r4.core.Timing}
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.prototype.getTiming = function() {
  return /** @type{?proto.google.fhir.r4.core.Timing} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Timing, 1));
};


/**
 * @param {?proto.google.fhir.r4.core.Timing|undefined} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement.TimingX} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.prototype.setTiming = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.google.fhir.r4.core.DeviceUseStatement.TimingX.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement.TimingX} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.prototype.clearTiming = function() {
  return this.setTiming(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.prototype.hasTiming = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Period period = 2;
 * @return {?proto.google.fhir.r4.core.Period}
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.prototype.getPeriod = function() {
  return /** @type{?proto.google.fhir.r4.core.Period} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Period, 2));
};


/**
 * @param {?proto.google.fhir.r4.core.Period|undefined} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement.TimingX} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.prototype.setPeriod = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.google.fhir.r4.core.DeviceUseStatement.TimingX.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement.TimingX} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.prototype.clearPeriod = function() {
  return this.setPeriod(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.prototype.hasPeriod = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional DateTime date_time = 3;
 * @return {?proto.google.fhir.r4.core.DateTime}
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.prototype.getDateTime = function() {
  return /** @type{?proto.google.fhir.r4.core.DateTime} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.DateTime, 3));
};


/**
 * @param {?proto.google.fhir.r4.core.DateTime|undefined} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement.TimingX} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.prototype.setDateTime = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.google.fhir.r4.core.DeviceUseStatement.TimingX.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement.TimingX} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.prototype.clearDateTime = function() {
  return this.setDateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DeviceUseStatement.TimingX.prototype.hasDateTime = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Id id = 1;
 * @return {?proto.google.fhir.r4.core.Id}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getId = function() {
  return /** @type{?proto.google.fhir.r4.core.Id} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Id, 1));
};


/**
 * @param {?proto.google.fhir.r4.core.Id|undefined} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Meta meta = 2;
 * @return {?proto.google.fhir.r4.core.Meta}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getMeta = function() {
  return /** @type{?proto.google.fhir.r4.core.Meta} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Meta, 2));
};


/**
 * @param {?proto.google.fhir.r4.core.Meta|undefined} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setMeta = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearMeta = function() {
  return this.setMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.hasMeta = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Uri implicit_rules = 3;
 * @return {?proto.google.fhir.r4.core.Uri}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getImplicitRules = function() {
  return /** @type{?proto.google.fhir.r4.core.Uri} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Uri, 3));
};


/**
 * @param {?proto.google.fhir.r4.core.Uri|undefined} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setImplicitRules = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearImplicitRules = function() {
  return this.setImplicitRules(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.hasImplicitRules = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Code language = 4;
 * @return {?proto.google.fhir.r4.core.Code}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getLanguage = function() {
  return /** @type{?proto.google.fhir.r4.core.Code} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Code, 4));
};


/**
 * @param {?proto.google.fhir.r4.core.Code|undefined} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setLanguage = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearLanguage = function() {
  return this.setLanguage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.hasLanguage = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Narrative text = 5;
 * @return {?proto.google.fhir.r4.core.Narrative}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getText = function() {
  return /** @type{?proto.google.fhir.r4.core.Narrative} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Narrative, 5));
};


/**
 * @param {?proto.google.fhir.r4.core.Narrative|undefined} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setText = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearText = function() {
  return this.setText(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.hasText = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * repeated google.protobuf.Any contained = 6;
 * @return {!Array<!proto.google.protobuf.Any>}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getContainedList = function() {
  return /** @type{!Array<!proto.google.protobuf.Any>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_protobuf_any_pb.Any, 6));
};


/**
 * @param {!Array<!proto.google.protobuf.Any>} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setContainedList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.google.protobuf.Any=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.protobuf.Any}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.addContained = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.google.protobuf.Any, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearContainedList = function() {
  return this.setContainedList([]);
};


/**
 * repeated Extension extension = 8;
 * @return {!Array<!proto.google.fhir.r4.core.Extension>}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getExtensionList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Extension>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Extension, 8));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Extension>} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setExtensionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Extension=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Extension}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.addExtension$ = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.google.fhir.r4.core.Extension, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearExtensionList = function() {
  return this.setExtensionList([]);
};


/**
 * repeated Extension modifier_extension = 9;
 * @return {!Array<!proto.google.fhir.r4.core.Extension>}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getModifierExtensionList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Extension>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Extension, 9));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Extension>} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setModifierExtensionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Extension=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Extension}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.addModifierExtension = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.google.fhir.r4.core.Extension, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearModifierExtensionList = function() {
  return this.setModifierExtensionList([]);
};


/**
 * repeated Identifier identifier = 10;
 * @return {!Array<!proto.google.fhir.r4.core.Identifier>}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getIdentifierList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Identifier>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Identifier, 10));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Identifier>} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setIdentifierList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Identifier=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Identifier}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.addIdentifier = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.google.fhir.r4.core.Identifier, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearIdentifierList = function() {
  return this.setIdentifierList([]);
};


/**
 * repeated Reference based_on = 11;
 * @return {!Array<!proto.google.fhir.r4.core.Reference>}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getBasedOnList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Reference>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Reference, 11));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Reference>} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setBasedOnList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Reference=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.addBasedOn = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.google.fhir.r4.core.Reference, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearBasedOnList = function() {
  return this.setBasedOnList([]);
};


/**
 * optional StatusCode status = 12;
 * @return {?proto.google.fhir.r4.core.DeviceUseStatement.StatusCode}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getStatus = function() {
  return /** @type{?proto.google.fhir.r4.core.DeviceUseStatement.StatusCode} */ (
    jspb.Message.getWrapperField(this, proto.google.fhir.r4.core.DeviceUseStatement.StatusCode, 12));
};


/**
 * @param {?proto.google.fhir.r4.core.DeviceUseStatement.StatusCode|undefined} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional Reference subject = 13;
 * @return {?proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getSubject = function() {
  return /** @type{?proto.google.fhir.r4.core.Reference} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Reference, 13));
};


/**
 * @param {?proto.google.fhir.r4.core.Reference|undefined} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setSubject = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearSubject = function() {
  return this.setSubject(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.hasSubject = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * repeated Reference derived_from = 14;
 * @return {!Array<!proto.google.fhir.r4.core.Reference>}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getDerivedFromList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Reference>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Reference, 14));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Reference>} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setDerivedFromList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 14, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Reference=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.addDerivedFrom = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 14, opt_value, proto.google.fhir.r4.core.Reference, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearDerivedFromList = function() {
  return this.setDerivedFromList([]);
};


/**
 * optional TimingX timing = 15;
 * @return {?proto.google.fhir.r4.core.DeviceUseStatement.TimingX}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getTiming = function() {
  return /** @type{?proto.google.fhir.r4.core.DeviceUseStatement.TimingX} */ (
    jspb.Message.getWrapperField(this, proto.google.fhir.r4.core.DeviceUseStatement.TimingX, 15));
};


/**
 * @param {?proto.google.fhir.r4.core.DeviceUseStatement.TimingX|undefined} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setTiming = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearTiming = function() {
  return this.setTiming(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.hasTiming = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional DateTime recorded_on = 16;
 * @return {?proto.google.fhir.r4.core.DateTime}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getRecordedOn = function() {
  return /** @type{?proto.google.fhir.r4.core.DateTime} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.DateTime, 16));
};


/**
 * @param {?proto.google.fhir.r4.core.DateTime|undefined} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setRecordedOn = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearRecordedOn = function() {
  return this.setRecordedOn(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.hasRecordedOn = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional Reference source = 17;
 * @return {?proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getSource = function() {
  return /** @type{?proto.google.fhir.r4.core.Reference} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Reference, 17));
};


/**
 * @param {?proto.google.fhir.r4.core.Reference|undefined} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setSource = function(value) {
  return jspb.Message.setWrapperField(this, 17, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearSource = function() {
  return this.setSource(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.hasSource = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional Reference device = 18;
 * @return {?proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getDevice = function() {
  return /** @type{?proto.google.fhir.r4.core.Reference} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Reference, 18));
};


/**
 * @param {?proto.google.fhir.r4.core.Reference|undefined} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setDevice = function(value) {
  return jspb.Message.setWrapperField(this, 18, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearDevice = function() {
  return this.setDevice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.hasDevice = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * repeated CodeableConcept reason_code = 19;
 * @return {!Array<!proto.google.fhir.r4.core.CodeableConcept>}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getReasonCodeList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.CodeableConcept>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.CodeableConcept, 19));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.CodeableConcept>} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setReasonCodeList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 19, value);
};


/**
 * @param {!proto.google.fhir.r4.core.CodeableConcept=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.CodeableConcept}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.addReasonCode = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 19, opt_value, proto.google.fhir.r4.core.CodeableConcept, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearReasonCodeList = function() {
  return this.setReasonCodeList([]);
};


/**
 * repeated Reference reason_reference = 20;
 * @return {!Array<!proto.google.fhir.r4.core.Reference>}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getReasonReferenceList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Reference>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Reference, 20));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Reference>} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setReasonReferenceList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 20, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Reference=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.addReasonReference = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 20, opt_value, proto.google.fhir.r4.core.Reference, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearReasonReferenceList = function() {
  return this.setReasonReferenceList([]);
};


/**
 * optional CodeableConcept body_site = 21;
 * @return {?proto.google.fhir.r4.core.CodeableConcept}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getBodySite = function() {
  return /** @type{?proto.google.fhir.r4.core.CodeableConcept} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.CodeableConcept, 21));
};


/**
 * @param {?proto.google.fhir.r4.core.CodeableConcept|undefined} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setBodySite = function(value) {
  return jspb.Message.setWrapperField(this, 21, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearBodySite = function() {
  return this.setBodySite(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.hasBodySite = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * repeated Annotation note = 22;
 * @return {!Array<!proto.google.fhir.r4.core.Annotation>}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.getNoteList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Annotation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Annotation, 22));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Annotation>} value
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
*/
proto.google.fhir.r4.core.DeviceUseStatement.prototype.setNoteList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 22, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Annotation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Annotation}
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.addNote = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 22, opt_value, proto.google.fhir.r4.core.Annotation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DeviceUseStatement} returns this
 */
proto.google.fhir.r4.core.DeviceUseStatement.prototype.clearNoteList = function() {
  return this.setNoteList([]);
};


goog.object.extend(exports, proto.google.fhir.r4.core);
