// source: proto/r4/core/resources/diagnostic_report.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
var proto_annotations_pb = require('../../../../proto/annotations_pb.js');
goog.object.extend(proto, proto_annotations_pb);
var proto_r4_core_codes_pb = require('../../../../proto/r4/core/codes_pb.js');
goog.object.extend(proto, proto_r4_core_codes_pb);
var proto_r4_core_datatypes_pb = require('../../../../proto/r4/core/datatypes_pb.js');
goog.object.extend(proto, proto_r4_core_datatypes_pb);
goog.exportSymbol('proto.google.fhir.r4.core.DiagnosticReport', null, global);
goog.exportSymbol('proto.google.fhir.r4.core.DiagnosticReport.EffectiveX', null, global);
goog.exportSymbol('proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.ChoiceCase', null, global);
goog.exportSymbol('proto.google.fhir.r4.core.DiagnosticReport.Media', null, global);
goog.exportSymbol('proto.google.fhir.r4.core.DiagnosticReport.StatusCode', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.fhir.r4.core.DiagnosticReport = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.fhir.r4.core.DiagnosticReport.repeatedFields_, null);
};
goog.inherits(proto.google.fhir.r4.core.DiagnosticReport, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.fhir.r4.core.DiagnosticReport.displayName = 'proto.google.fhir.r4.core.DiagnosticReport';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.fhir.r4.core.DiagnosticReport.StatusCode = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.fhir.r4.core.DiagnosticReport.StatusCode.repeatedFields_, null);
};
goog.inherits(proto.google.fhir.r4.core.DiagnosticReport.StatusCode, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.fhir.r4.core.DiagnosticReport.StatusCode.displayName = 'proto.google.fhir.r4.core.DiagnosticReport.StatusCode';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.fhir.r4.core.DiagnosticReport.EffectiveX = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.oneofGroups_);
};
goog.inherits(proto.google.fhir.r4.core.DiagnosticReport.EffectiveX, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.displayName = 'proto.google.fhir.r4.core.DiagnosticReport.EffectiveX';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.fhir.r4.core.DiagnosticReport.Media = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.fhir.r4.core.DiagnosticReport.Media.repeatedFields_, null);
};
goog.inherits(proto.google.fhir.r4.core.DiagnosticReport.Media, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.fhir.r4.core.DiagnosticReport.Media.displayName = 'proto.google.fhir.r4.core.DiagnosticReport.Media';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.fhir.r4.core.DiagnosticReport.repeatedFields_ = [6,8,9,10,11,13,19,20,21,22,23,24,26,27];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.toObject = function(opt_includeInstance) {
  return proto.google.fhir.r4.core.DiagnosticReport.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.fhir.r4.core.DiagnosticReport} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.DiagnosticReport.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && proto_r4_core_datatypes_pb.Id.toObject(includeInstance, f),
    meta: (f = msg.getMeta()) && proto_r4_core_datatypes_pb.Meta.toObject(includeInstance, f),
    implicitRules: (f = msg.getImplicitRules()) && proto_r4_core_datatypes_pb.Uri.toObject(includeInstance, f),
    language: (f = msg.getLanguage()) && proto_r4_core_datatypes_pb.Code.toObject(includeInstance, f),
    text: (f = msg.getText()) && proto_r4_core_datatypes_pb.Narrative.toObject(includeInstance, f),
    containedList: jspb.Message.toObjectList(msg.getContainedList(),
    google_protobuf_any_pb.Any.toObject, includeInstance),
    extensionList: jspb.Message.toObjectList(msg.getExtensionList(),
    proto_r4_core_datatypes_pb.Extension.toObject, includeInstance),
    modifierExtensionList: jspb.Message.toObjectList(msg.getModifierExtensionList(),
    proto_r4_core_datatypes_pb.Extension.toObject, includeInstance),
    identifierList: jspb.Message.toObjectList(msg.getIdentifierList(),
    proto_r4_core_datatypes_pb.Identifier.toObject, includeInstance),
    basedOnList: jspb.Message.toObjectList(msg.getBasedOnList(),
    proto_r4_core_datatypes_pb.Reference.toObject, includeInstance),
    status: (f = msg.getStatus()) && proto.google.fhir.r4.core.DiagnosticReport.StatusCode.toObject(includeInstance, f),
    categoryList: jspb.Message.toObjectList(msg.getCategoryList(),
    proto_r4_core_datatypes_pb.CodeableConcept.toObject, includeInstance),
    code: (f = msg.getCode()) && proto_r4_core_datatypes_pb.CodeableConcept.toObject(includeInstance, f),
    subject: (f = msg.getSubject()) && proto_r4_core_datatypes_pb.Reference.toObject(includeInstance, f),
    encounter: (f = msg.getEncounter()) && proto_r4_core_datatypes_pb.Reference.toObject(includeInstance, f),
    effective: (f = msg.getEffective()) && proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.toObject(includeInstance, f),
    issued: (f = msg.getIssued()) && proto_r4_core_datatypes_pb.Instant.toObject(includeInstance, f),
    performerList: jspb.Message.toObjectList(msg.getPerformerList(),
    proto_r4_core_datatypes_pb.Reference.toObject, includeInstance),
    resultsInterpreterList: jspb.Message.toObjectList(msg.getResultsInterpreterList(),
    proto_r4_core_datatypes_pb.Reference.toObject, includeInstance),
    specimenList: jspb.Message.toObjectList(msg.getSpecimenList(),
    proto_r4_core_datatypes_pb.Reference.toObject, includeInstance),
    resultList: jspb.Message.toObjectList(msg.getResultList(),
    proto_r4_core_datatypes_pb.Reference.toObject, includeInstance),
    imagingStudyList: jspb.Message.toObjectList(msg.getImagingStudyList(),
    proto_r4_core_datatypes_pb.Reference.toObject, includeInstance),
    mediaList: jspb.Message.toObjectList(msg.getMediaList(),
    proto.google.fhir.r4.core.DiagnosticReport.Media.toObject, includeInstance),
    conclusion: (f = msg.getConclusion()) && proto_r4_core_datatypes_pb.String.toObject(includeInstance, f),
    conclusionCodeList: jspb.Message.toObjectList(msg.getConclusionCodeList(),
    proto_r4_core_datatypes_pb.CodeableConcept.toObject, includeInstance),
    presentedFormList: jspb.Message.toObjectList(msg.getPresentedFormList(),
    proto_r4_core_datatypes_pb.Attachment.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport}
 */
proto.google.fhir.r4.core.DiagnosticReport.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.fhir.r4.core.DiagnosticReport;
  return proto.google.fhir.r4.core.DiagnosticReport.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.fhir.r4.core.DiagnosticReport} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport}
 */
proto.google.fhir.r4.core.DiagnosticReport.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto_r4_core_datatypes_pb.Id;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Id.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = new proto_r4_core_datatypes_pb.Meta;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Meta.deserializeBinaryFromReader);
      msg.setMeta(value);
      break;
    case 3:
      var value = new proto_r4_core_datatypes_pb.Uri;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Uri.deserializeBinaryFromReader);
      msg.setImplicitRules(value);
      break;
    case 4:
      var value = new proto_r4_core_datatypes_pb.Code;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Code.deserializeBinaryFromReader);
      msg.setLanguage(value);
      break;
    case 5:
      var value = new proto_r4_core_datatypes_pb.Narrative;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Narrative.deserializeBinaryFromReader);
      msg.setText(value);
      break;
    case 6:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.addContained(value);
      break;
    case 8:
      var value = new proto_r4_core_datatypes_pb.Extension;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Extension.deserializeBinaryFromReader);
      msg.addExtension$(value);
      break;
    case 9:
      var value = new proto_r4_core_datatypes_pb.Extension;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Extension.deserializeBinaryFromReader);
      msg.addModifierExtension(value);
      break;
    case 10:
      var value = new proto_r4_core_datatypes_pb.Identifier;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Identifier.deserializeBinaryFromReader);
      msg.addIdentifier(value);
      break;
    case 11:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.addBasedOn(value);
      break;
    case 12:
      var value = new proto.google.fhir.r4.core.DiagnosticReport.StatusCode;
      reader.readMessage(value,proto.google.fhir.r4.core.DiagnosticReport.StatusCode.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 13:
      var value = new proto_r4_core_datatypes_pb.CodeableConcept;
      reader.readMessage(value,proto_r4_core_datatypes_pb.CodeableConcept.deserializeBinaryFromReader);
      msg.addCategory(value);
      break;
    case 14:
      var value = new proto_r4_core_datatypes_pb.CodeableConcept;
      reader.readMessage(value,proto_r4_core_datatypes_pb.CodeableConcept.deserializeBinaryFromReader);
      msg.setCode(value);
      break;
    case 15:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.setSubject(value);
      break;
    case 16:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.setEncounter(value);
      break;
    case 17:
      var value = new proto.google.fhir.r4.core.DiagnosticReport.EffectiveX;
      reader.readMessage(value,proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.deserializeBinaryFromReader);
      msg.setEffective(value);
      break;
    case 18:
      var value = new proto_r4_core_datatypes_pb.Instant;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Instant.deserializeBinaryFromReader);
      msg.setIssued(value);
      break;
    case 19:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.addPerformer(value);
      break;
    case 20:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.addResultsInterpreter(value);
      break;
    case 21:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.addSpecimen(value);
      break;
    case 22:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.addResult(value);
      break;
    case 23:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.addImagingStudy(value);
      break;
    case 24:
      var value = new proto.google.fhir.r4.core.DiagnosticReport.Media;
      reader.readMessage(value,proto.google.fhir.r4.core.DiagnosticReport.Media.deserializeBinaryFromReader);
      msg.addMedia(value);
      break;
    case 25:
      var value = new proto_r4_core_datatypes_pb.String;
      reader.readMessage(value,proto_r4_core_datatypes_pb.String.deserializeBinaryFromReader);
      msg.setConclusion(value);
      break;
    case 26:
      var value = new proto_r4_core_datatypes_pb.CodeableConcept;
      reader.readMessage(value,proto_r4_core_datatypes_pb.CodeableConcept.deserializeBinaryFromReader);
      msg.addConclusionCode(value);
      break;
    case 27:
      var value = new proto_r4_core_datatypes_pb.Attachment;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Attachment.deserializeBinaryFromReader);
      msg.addPresentedForm(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.fhir.r4.core.DiagnosticReport.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.fhir.r4.core.DiagnosticReport} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.DiagnosticReport.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto_r4_core_datatypes_pb.Id.serializeBinaryToWriter
    );
  }
  f = message.getMeta();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto_r4_core_datatypes_pb.Meta.serializeBinaryToWriter
    );
  }
  f = message.getImplicitRules();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto_r4_core_datatypes_pb.Uri.serializeBinaryToWriter
    );
  }
  f = message.getLanguage();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto_r4_core_datatypes_pb.Code.serializeBinaryToWriter
    );
  }
  f = message.getText();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto_r4_core_datatypes_pb.Narrative.serializeBinaryToWriter
    );
  }
  f = message.getContainedList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
  f = message.getExtensionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      proto_r4_core_datatypes_pb.Extension.serializeBinaryToWriter
    );
  }
  f = message.getModifierExtensionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      proto_r4_core_datatypes_pb.Extension.serializeBinaryToWriter
    );
  }
  f = message.getIdentifierList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      proto_r4_core_datatypes_pb.Identifier.serializeBinaryToWriter
    );
  }
  f = message.getBasedOnList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.google.fhir.r4.core.DiagnosticReport.StatusCode.serializeBinaryToWriter
    );
  }
  f = message.getCategoryList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      proto_r4_core_datatypes_pb.CodeableConcept.serializeBinaryToWriter
    );
  }
  f = message.getCode();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      proto_r4_core_datatypes_pb.CodeableConcept.serializeBinaryToWriter
    );
  }
  f = message.getSubject();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getEncounter();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getEffective();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.serializeBinaryToWriter
    );
  }
  f = message.getIssued();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      proto_r4_core_datatypes_pb.Instant.serializeBinaryToWriter
    );
  }
  f = message.getPerformerList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      19,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getResultsInterpreterList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      20,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getSpecimenList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      21,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getResultList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      22,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getImagingStudyList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      23,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getMediaList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      24,
      f,
      proto.google.fhir.r4.core.DiagnosticReport.Media.serializeBinaryToWriter
    );
  }
  f = message.getConclusion();
  if (f != null) {
    writer.writeMessage(
      25,
      f,
      proto_r4_core_datatypes_pb.String.serializeBinaryToWriter
    );
  }
  f = message.getConclusionCodeList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      26,
      f,
      proto_r4_core_datatypes_pb.CodeableConcept.serializeBinaryToWriter
    );
  }
  f = message.getPresentedFormList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      27,
      f,
      proto_r4_core_datatypes_pb.Attachment.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.fhir.r4.core.DiagnosticReport.StatusCode.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.fhir.r4.core.DiagnosticReport.StatusCode.prototype.toObject = function(opt_includeInstance) {
  return proto.google.fhir.r4.core.DiagnosticReport.StatusCode.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.fhir.r4.core.DiagnosticReport.StatusCode} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.DiagnosticReport.StatusCode.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: jspb.Message.getFieldWithDefault(msg, 1, 0),
    id: (f = msg.getId()) && proto_r4_core_datatypes_pb.String.toObject(includeInstance, f),
    extensionList: jspb.Message.toObjectList(msg.getExtensionList(),
    proto_r4_core_datatypes_pb.Extension.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.StatusCode}
 */
proto.google.fhir.r4.core.DiagnosticReport.StatusCode.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.fhir.r4.core.DiagnosticReport.StatusCode;
  return proto.google.fhir.r4.core.DiagnosticReport.StatusCode.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.fhir.r4.core.DiagnosticReport.StatusCode} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.StatusCode}
 */
proto.google.fhir.r4.core.DiagnosticReport.StatusCode.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.google.fhir.r4.core.DiagnosticReportStatusCode.Value} */ (reader.readEnum());
      msg.setValue(value);
      break;
    case 2:
      var value = new proto_r4_core_datatypes_pb.String;
      reader.readMessage(value,proto_r4_core_datatypes_pb.String.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 3:
      var value = new proto_r4_core_datatypes_pb.Extension;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Extension.deserializeBinaryFromReader);
      msg.addExtension$(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.fhir.r4.core.DiagnosticReport.StatusCode.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.fhir.r4.core.DiagnosticReport.StatusCode.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.fhir.r4.core.DiagnosticReport.StatusCode} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.DiagnosticReport.StatusCode.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValue();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto_r4_core_datatypes_pb.String.serializeBinaryToWriter
    );
  }
  f = message.getExtensionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto_r4_core_datatypes_pb.Extension.serializeBinaryToWriter
    );
  }
};


/**
 * optional DiagnosticReportStatusCode.Value value = 1;
 * @return {!proto.google.fhir.r4.core.DiagnosticReportStatusCode.Value}
 */
proto.google.fhir.r4.core.DiagnosticReport.StatusCode.prototype.getValue = function() {
  return /** @type {!proto.google.fhir.r4.core.DiagnosticReportStatusCode.Value} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.google.fhir.r4.core.DiagnosticReportStatusCode.Value} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.StatusCode} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.StatusCode.prototype.setValue = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional String id = 2;
 * @return {?proto.google.fhir.r4.core.String}
 */
proto.google.fhir.r4.core.DiagnosticReport.StatusCode.prototype.getId = function() {
  return /** @type{?proto.google.fhir.r4.core.String} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.String, 2));
};


/**
 * @param {?proto.google.fhir.r4.core.String|undefined} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.StatusCode} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.StatusCode.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.StatusCode} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.StatusCode.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DiagnosticReport.StatusCode.prototype.hasId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated Extension extension = 3;
 * @return {!Array<!proto.google.fhir.r4.core.Extension>}
 */
proto.google.fhir.r4.core.DiagnosticReport.StatusCode.prototype.getExtensionList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Extension>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Extension, 3));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Extension>} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.StatusCode} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.StatusCode.prototype.setExtensionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Extension=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Extension}
 */
proto.google.fhir.r4.core.DiagnosticReport.StatusCode.prototype.addExtension$ = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.google.fhir.r4.core.Extension, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.StatusCode} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.StatusCode.prototype.clearExtensionList = function() {
  return this.setExtensionList([]);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.ChoiceCase = {
  CHOICE_NOT_SET: 0,
  DATE_TIME: 1,
  PERIOD: 2
};

/**
 * @return {proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.ChoiceCase}
 */
proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.prototype.getChoiceCase = function() {
  return /** @type {proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.ChoiceCase} */(jspb.Message.computeOneofCase(this, proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.prototype.toObject = function(opt_includeInstance) {
  return proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.fhir.r4.core.DiagnosticReport.EffectiveX} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.toObject = function(includeInstance, msg) {
  var f, obj = {
    dateTime: (f = msg.getDateTime()) && proto_r4_core_datatypes_pb.DateTime.toObject(includeInstance, f),
    period: (f = msg.getPeriod()) && proto_r4_core_datatypes_pb.Period.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.EffectiveX}
 */
proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.fhir.r4.core.DiagnosticReport.EffectiveX;
  return proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.fhir.r4.core.DiagnosticReport.EffectiveX} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.EffectiveX}
 */
proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto_r4_core_datatypes_pb.DateTime;
      reader.readMessage(value,proto_r4_core_datatypes_pb.DateTime.deserializeBinaryFromReader);
      msg.setDateTime(value);
      break;
    case 2:
      var value = new proto_r4_core_datatypes_pb.Period;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Period.deserializeBinaryFromReader);
      msg.setPeriod(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.fhir.r4.core.DiagnosticReport.EffectiveX} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDateTime();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto_r4_core_datatypes_pb.DateTime.serializeBinaryToWriter
    );
  }
  f = message.getPeriod();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto_r4_core_datatypes_pb.Period.serializeBinaryToWriter
    );
  }
};


/**
 * optional DateTime date_time = 1;
 * @return {?proto.google.fhir.r4.core.DateTime}
 */
proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.prototype.getDateTime = function() {
  return /** @type{?proto.google.fhir.r4.core.DateTime} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.DateTime, 1));
};


/**
 * @param {?proto.google.fhir.r4.core.DateTime|undefined} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.EffectiveX} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.prototype.setDateTime = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.EffectiveX} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.prototype.clearDateTime = function() {
  return this.setDateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.prototype.hasDateTime = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Period period = 2;
 * @return {?proto.google.fhir.r4.core.Period}
 */
proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.prototype.getPeriod = function() {
  return /** @type{?proto.google.fhir.r4.core.Period} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Period, 2));
};


/**
 * @param {?proto.google.fhir.r4.core.Period|undefined} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.EffectiveX} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.prototype.setPeriod = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.EffectiveX} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.prototype.clearPeriod = function() {
  return this.setPeriod(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DiagnosticReport.EffectiveX.prototype.hasPeriod = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.toObject = function(opt_includeInstance) {
  return proto.google.fhir.r4.core.DiagnosticReport.Media.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.fhir.r4.core.DiagnosticReport.Media} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && proto_r4_core_datatypes_pb.String.toObject(includeInstance, f),
    extensionList: jspb.Message.toObjectList(msg.getExtensionList(),
    proto_r4_core_datatypes_pb.Extension.toObject, includeInstance),
    modifierExtensionList: jspb.Message.toObjectList(msg.getModifierExtensionList(),
    proto_r4_core_datatypes_pb.Extension.toObject, includeInstance),
    comment: (f = msg.getComment()) && proto_r4_core_datatypes_pb.String.toObject(includeInstance, f),
    link: (f = msg.getLink()) && proto_r4_core_datatypes_pb.Reference.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.Media}
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.fhir.r4.core.DiagnosticReport.Media;
  return proto.google.fhir.r4.core.DiagnosticReport.Media.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.fhir.r4.core.DiagnosticReport.Media} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.Media}
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto_r4_core_datatypes_pb.String;
      reader.readMessage(value,proto_r4_core_datatypes_pb.String.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = new proto_r4_core_datatypes_pb.Extension;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Extension.deserializeBinaryFromReader);
      msg.addExtension$(value);
      break;
    case 3:
      var value = new proto_r4_core_datatypes_pb.Extension;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Extension.deserializeBinaryFromReader);
      msg.addModifierExtension(value);
      break;
    case 4:
      var value = new proto_r4_core_datatypes_pb.String;
      reader.readMessage(value,proto_r4_core_datatypes_pb.String.deserializeBinaryFromReader);
      msg.setComment(value);
      break;
    case 5:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.setLink(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.fhir.r4.core.DiagnosticReport.Media.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.fhir.r4.core.DiagnosticReport.Media} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto_r4_core_datatypes_pb.String.serializeBinaryToWriter
    );
  }
  f = message.getExtensionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto_r4_core_datatypes_pb.Extension.serializeBinaryToWriter
    );
  }
  f = message.getModifierExtensionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto_r4_core_datatypes_pb.Extension.serializeBinaryToWriter
    );
  }
  f = message.getComment();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto_r4_core_datatypes_pb.String.serializeBinaryToWriter
    );
  }
  f = message.getLink();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
};


/**
 * optional String id = 1;
 * @return {?proto.google.fhir.r4.core.String}
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.getId = function() {
  return /** @type{?proto.google.fhir.r4.core.String} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.String, 1));
};


/**
 * @param {?proto.google.fhir.r4.core.String|undefined} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.Media} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.Media} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Extension extension = 2;
 * @return {!Array<!proto.google.fhir.r4.core.Extension>}
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.getExtensionList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Extension>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Extension, 2));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Extension>} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.Media} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.setExtensionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Extension=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Extension}
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.addExtension$ = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.google.fhir.r4.core.Extension, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.Media} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.clearExtensionList = function() {
  return this.setExtensionList([]);
};


/**
 * repeated Extension modifier_extension = 3;
 * @return {!Array<!proto.google.fhir.r4.core.Extension>}
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.getModifierExtensionList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Extension>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Extension, 3));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Extension>} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.Media} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.setModifierExtensionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Extension=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Extension}
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.addModifierExtension = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.google.fhir.r4.core.Extension, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.Media} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.clearModifierExtensionList = function() {
  return this.setModifierExtensionList([]);
};


/**
 * optional String comment = 4;
 * @return {?proto.google.fhir.r4.core.String}
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.getComment = function() {
  return /** @type{?proto.google.fhir.r4.core.String} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.String, 4));
};


/**
 * @param {?proto.google.fhir.r4.core.String|undefined} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.Media} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.setComment = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.Media} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.clearComment = function() {
  return this.setComment(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.hasComment = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Reference link = 5;
 * @return {?proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.getLink = function() {
  return /** @type{?proto.google.fhir.r4.core.Reference} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Reference, 5));
};


/**
 * @param {?proto.google.fhir.r4.core.Reference|undefined} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.Media} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.setLink = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.Media} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.clearLink = function() {
  return this.setLink(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DiagnosticReport.Media.prototype.hasLink = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional Id id = 1;
 * @return {?proto.google.fhir.r4.core.Id}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getId = function() {
  return /** @type{?proto.google.fhir.r4.core.Id} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Id, 1));
};


/**
 * @param {?proto.google.fhir.r4.core.Id|undefined} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Meta meta = 2;
 * @return {?proto.google.fhir.r4.core.Meta}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getMeta = function() {
  return /** @type{?proto.google.fhir.r4.core.Meta} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Meta, 2));
};


/**
 * @param {?proto.google.fhir.r4.core.Meta|undefined} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setMeta = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearMeta = function() {
  return this.setMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.hasMeta = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Uri implicit_rules = 3;
 * @return {?proto.google.fhir.r4.core.Uri}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getImplicitRules = function() {
  return /** @type{?proto.google.fhir.r4.core.Uri} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Uri, 3));
};


/**
 * @param {?proto.google.fhir.r4.core.Uri|undefined} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setImplicitRules = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearImplicitRules = function() {
  return this.setImplicitRules(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.hasImplicitRules = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Code language = 4;
 * @return {?proto.google.fhir.r4.core.Code}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getLanguage = function() {
  return /** @type{?proto.google.fhir.r4.core.Code} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Code, 4));
};


/**
 * @param {?proto.google.fhir.r4.core.Code|undefined} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setLanguage = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearLanguage = function() {
  return this.setLanguage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.hasLanguage = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Narrative text = 5;
 * @return {?proto.google.fhir.r4.core.Narrative}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getText = function() {
  return /** @type{?proto.google.fhir.r4.core.Narrative} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Narrative, 5));
};


/**
 * @param {?proto.google.fhir.r4.core.Narrative|undefined} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setText = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearText = function() {
  return this.setText(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.hasText = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * repeated google.protobuf.Any contained = 6;
 * @return {!Array<!proto.google.protobuf.Any>}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getContainedList = function() {
  return /** @type{!Array<!proto.google.protobuf.Any>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_protobuf_any_pb.Any, 6));
};


/**
 * @param {!Array<!proto.google.protobuf.Any>} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setContainedList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.google.protobuf.Any=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.protobuf.Any}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.addContained = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.google.protobuf.Any, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearContainedList = function() {
  return this.setContainedList([]);
};


/**
 * repeated Extension extension = 8;
 * @return {!Array<!proto.google.fhir.r4.core.Extension>}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getExtensionList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Extension>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Extension, 8));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Extension>} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setExtensionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Extension=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Extension}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.addExtension$ = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.google.fhir.r4.core.Extension, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearExtensionList = function() {
  return this.setExtensionList([]);
};


/**
 * repeated Extension modifier_extension = 9;
 * @return {!Array<!proto.google.fhir.r4.core.Extension>}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getModifierExtensionList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Extension>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Extension, 9));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Extension>} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setModifierExtensionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Extension=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Extension}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.addModifierExtension = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.google.fhir.r4.core.Extension, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearModifierExtensionList = function() {
  return this.setModifierExtensionList([]);
};


/**
 * repeated Identifier identifier = 10;
 * @return {!Array<!proto.google.fhir.r4.core.Identifier>}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getIdentifierList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Identifier>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Identifier, 10));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Identifier>} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setIdentifierList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Identifier=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Identifier}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.addIdentifier = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.google.fhir.r4.core.Identifier, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearIdentifierList = function() {
  return this.setIdentifierList([]);
};


/**
 * repeated Reference based_on = 11;
 * @return {!Array<!proto.google.fhir.r4.core.Reference>}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getBasedOnList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Reference>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Reference, 11));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Reference>} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setBasedOnList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Reference=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.addBasedOn = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.google.fhir.r4.core.Reference, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearBasedOnList = function() {
  return this.setBasedOnList([]);
};


/**
 * optional StatusCode status = 12;
 * @return {?proto.google.fhir.r4.core.DiagnosticReport.StatusCode}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getStatus = function() {
  return /** @type{?proto.google.fhir.r4.core.DiagnosticReport.StatusCode} */ (
    jspb.Message.getWrapperField(this, proto.google.fhir.r4.core.DiagnosticReport.StatusCode, 12));
};


/**
 * @param {?proto.google.fhir.r4.core.DiagnosticReport.StatusCode|undefined} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * repeated CodeableConcept category = 13;
 * @return {!Array<!proto.google.fhir.r4.core.CodeableConcept>}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getCategoryList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.CodeableConcept>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.CodeableConcept, 13));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.CodeableConcept>} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setCategoryList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.google.fhir.r4.core.CodeableConcept=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.CodeableConcept}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.addCategory = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.google.fhir.r4.core.CodeableConcept, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearCategoryList = function() {
  return this.setCategoryList([]);
};


/**
 * optional CodeableConcept code = 14;
 * @return {?proto.google.fhir.r4.core.CodeableConcept}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getCode = function() {
  return /** @type{?proto.google.fhir.r4.core.CodeableConcept} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.CodeableConcept, 14));
};


/**
 * @param {?proto.google.fhir.r4.core.CodeableConcept|undefined} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setCode = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearCode = function() {
  return this.setCode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.hasCode = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional Reference subject = 15;
 * @return {?proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getSubject = function() {
  return /** @type{?proto.google.fhir.r4.core.Reference} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Reference, 15));
};


/**
 * @param {?proto.google.fhir.r4.core.Reference|undefined} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setSubject = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearSubject = function() {
  return this.setSubject(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.hasSubject = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional Reference encounter = 16;
 * @return {?proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getEncounter = function() {
  return /** @type{?proto.google.fhir.r4.core.Reference} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Reference, 16));
};


/**
 * @param {?proto.google.fhir.r4.core.Reference|undefined} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setEncounter = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearEncounter = function() {
  return this.setEncounter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.hasEncounter = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional EffectiveX effective = 17;
 * @return {?proto.google.fhir.r4.core.DiagnosticReport.EffectiveX}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getEffective = function() {
  return /** @type{?proto.google.fhir.r4.core.DiagnosticReport.EffectiveX} */ (
    jspb.Message.getWrapperField(this, proto.google.fhir.r4.core.DiagnosticReport.EffectiveX, 17));
};


/**
 * @param {?proto.google.fhir.r4.core.DiagnosticReport.EffectiveX|undefined} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setEffective = function(value) {
  return jspb.Message.setWrapperField(this, 17, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearEffective = function() {
  return this.setEffective(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.hasEffective = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional Instant issued = 18;
 * @return {?proto.google.fhir.r4.core.Instant}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getIssued = function() {
  return /** @type{?proto.google.fhir.r4.core.Instant} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Instant, 18));
};


/**
 * @param {?proto.google.fhir.r4.core.Instant|undefined} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setIssued = function(value) {
  return jspb.Message.setWrapperField(this, 18, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearIssued = function() {
  return this.setIssued(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.hasIssued = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * repeated Reference performer = 19;
 * @return {!Array<!proto.google.fhir.r4.core.Reference>}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getPerformerList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Reference>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Reference, 19));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Reference>} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setPerformerList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 19, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Reference=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.addPerformer = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 19, opt_value, proto.google.fhir.r4.core.Reference, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearPerformerList = function() {
  return this.setPerformerList([]);
};


/**
 * repeated Reference results_interpreter = 20;
 * @return {!Array<!proto.google.fhir.r4.core.Reference>}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getResultsInterpreterList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Reference>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Reference, 20));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Reference>} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setResultsInterpreterList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 20, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Reference=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.addResultsInterpreter = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 20, opt_value, proto.google.fhir.r4.core.Reference, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearResultsInterpreterList = function() {
  return this.setResultsInterpreterList([]);
};


/**
 * repeated Reference specimen = 21;
 * @return {!Array<!proto.google.fhir.r4.core.Reference>}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getSpecimenList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Reference>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Reference, 21));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Reference>} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setSpecimenList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 21, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Reference=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.addSpecimen = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 21, opt_value, proto.google.fhir.r4.core.Reference, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearSpecimenList = function() {
  return this.setSpecimenList([]);
};


/**
 * repeated Reference result = 22;
 * @return {!Array<!proto.google.fhir.r4.core.Reference>}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getResultList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Reference>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Reference, 22));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Reference>} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setResultList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 22, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Reference=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.addResult = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 22, opt_value, proto.google.fhir.r4.core.Reference, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearResultList = function() {
  return this.setResultList([]);
};


/**
 * repeated Reference imaging_study = 23;
 * @return {!Array<!proto.google.fhir.r4.core.Reference>}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getImagingStudyList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Reference>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Reference, 23));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Reference>} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setImagingStudyList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 23, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Reference=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.addImagingStudy = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 23, opt_value, proto.google.fhir.r4.core.Reference, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearImagingStudyList = function() {
  return this.setImagingStudyList([]);
};


/**
 * repeated Media media = 24;
 * @return {!Array<!proto.google.fhir.r4.core.DiagnosticReport.Media>}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getMediaList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.DiagnosticReport.Media>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.fhir.r4.core.DiagnosticReport.Media, 24));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.DiagnosticReport.Media>} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setMediaList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 24, value);
};


/**
 * @param {!proto.google.fhir.r4.core.DiagnosticReport.Media=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.DiagnosticReport.Media}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.addMedia = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 24, opt_value, proto.google.fhir.r4.core.DiagnosticReport.Media, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearMediaList = function() {
  return this.setMediaList([]);
};


/**
 * optional String conclusion = 25;
 * @return {?proto.google.fhir.r4.core.String}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getConclusion = function() {
  return /** @type{?proto.google.fhir.r4.core.String} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.String, 25));
};


/**
 * @param {?proto.google.fhir.r4.core.String|undefined} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setConclusion = function(value) {
  return jspb.Message.setWrapperField(this, 25, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearConclusion = function() {
  return this.setConclusion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.hasConclusion = function() {
  return jspb.Message.getField(this, 25) != null;
};


/**
 * repeated CodeableConcept conclusion_code = 26;
 * @return {!Array<!proto.google.fhir.r4.core.CodeableConcept>}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getConclusionCodeList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.CodeableConcept>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.CodeableConcept, 26));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.CodeableConcept>} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setConclusionCodeList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 26, value);
};


/**
 * @param {!proto.google.fhir.r4.core.CodeableConcept=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.CodeableConcept}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.addConclusionCode = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 26, opt_value, proto.google.fhir.r4.core.CodeableConcept, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearConclusionCodeList = function() {
  return this.setConclusionCodeList([]);
};


/**
 * repeated Attachment presented_form = 27;
 * @return {!Array<!proto.google.fhir.r4.core.Attachment>}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.getPresentedFormList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Attachment>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Attachment, 27));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Attachment>} value
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
*/
proto.google.fhir.r4.core.DiagnosticReport.prototype.setPresentedFormList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 27, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Attachment=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Attachment}
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.addPresentedForm = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 27, opt_value, proto.google.fhir.r4.core.Attachment, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.DiagnosticReport} returns this
 */
proto.google.fhir.r4.core.DiagnosticReport.prototype.clearPresentedFormList = function() {
  return this.setPresentedFormList([]);
};


goog.object.extend(exports, proto.google.fhir.r4.core);
