// source: proto/r4/core/resources/communication.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
var proto_annotations_pb = require('../../../../proto/annotations_pb.js');
goog.object.extend(proto, proto_annotations_pb);
var proto_r4_core_codes_pb = require('../../../../proto/r4/core/codes_pb.js');
goog.object.extend(proto, proto_r4_core_codes_pb);
var proto_r4_core_datatypes_pb = require('../../../../proto/r4/core/datatypes_pb.js');
goog.object.extend(proto, proto_r4_core_datatypes_pb);
goog.exportSymbol('proto.google.fhir.r4.core.Communication', null, global);
goog.exportSymbol('proto.google.fhir.r4.core.Communication.Payload', null, global);
goog.exportSymbol('proto.google.fhir.r4.core.Communication.Payload.ContentX', null, global);
goog.exportSymbol('proto.google.fhir.r4.core.Communication.Payload.ContentX.ChoiceCase', null, global);
goog.exportSymbol('proto.google.fhir.r4.core.Communication.PriorityCode', null, global);
goog.exportSymbol('proto.google.fhir.r4.core.Communication.StatusCode', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.fhir.r4.core.Communication = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.fhir.r4.core.Communication.repeatedFields_, null);
};
goog.inherits(proto.google.fhir.r4.core.Communication, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.fhir.r4.core.Communication.displayName = 'proto.google.fhir.r4.core.Communication';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.fhir.r4.core.Communication.StatusCode = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.fhir.r4.core.Communication.StatusCode.repeatedFields_, null);
};
goog.inherits(proto.google.fhir.r4.core.Communication.StatusCode, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.fhir.r4.core.Communication.StatusCode.displayName = 'proto.google.fhir.r4.core.Communication.StatusCode';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.fhir.r4.core.Communication.PriorityCode = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.fhir.r4.core.Communication.PriorityCode.repeatedFields_, null);
};
goog.inherits(proto.google.fhir.r4.core.Communication.PriorityCode, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.fhir.r4.core.Communication.PriorityCode.displayName = 'proto.google.fhir.r4.core.Communication.PriorityCode';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.fhir.r4.core.Communication.Payload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.fhir.r4.core.Communication.Payload.repeatedFields_, null);
};
goog.inherits(proto.google.fhir.r4.core.Communication.Payload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.fhir.r4.core.Communication.Payload.displayName = 'proto.google.fhir.r4.core.Communication.Payload';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.google.fhir.r4.core.Communication.Payload.ContentX.oneofGroups_);
};
goog.inherits(proto.google.fhir.r4.core.Communication.Payload.ContentX, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.fhir.r4.core.Communication.Payload.ContentX.displayName = 'proto.google.fhir.r4.core.Communication.Payload.ContentX';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.fhir.r4.core.Communication.repeatedFields_ = [6,8,9,10,11,12,13,14,15,18,20,23,27,29,30,31,32];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.fhir.r4.core.Communication.prototype.toObject = function(opt_includeInstance) {
  return proto.google.fhir.r4.core.Communication.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.fhir.r4.core.Communication} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.Communication.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && proto_r4_core_datatypes_pb.Id.toObject(includeInstance, f),
    meta: (f = msg.getMeta()) && proto_r4_core_datatypes_pb.Meta.toObject(includeInstance, f),
    implicitRules: (f = msg.getImplicitRules()) && proto_r4_core_datatypes_pb.Uri.toObject(includeInstance, f),
    language: (f = msg.getLanguage()) && proto_r4_core_datatypes_pb.Code.toObject(includeInstance, f),
    text: (f = msg.getText()) && proto_r4_core_datatypes_pb.Narrative.toObject(includeInstance, f),
    containedList: jspb.Message.toObjectList(msg.getContainedList(),
    google_protobuf_any_pb.Any.toObject, includeInstance),
    extensionList: jspb.Message.toObjectList(msg.getExtensionList(),
    proto_r4_core_datatypes_pb.Extension.toObject, includeInstance),
    modifierExtensionList: jspb.Message.toObjectList(msg.getModifierExtensionList(),
    proto_r4_core_datatypes_pb.Extension.toObject, includeInstance),
    identifierList: jspb.Message.toObjectList(msg.getIdentifierList(),
    proto_r4_core_datatypes_pb.Identifier.toObject, includeInstance),
    instantiatesCanonicalList: jspb.Message.toObjectList(msg.getInstantiatesCanonicalList(),
    proto_r4_core_datatypes_pb.Canonical.toObject, includeInstance),
    instantiatesUriList: jspb.Message.toObjectList(msg.getInstantiatesUriList(),
    proto_r4_core_datatypes_pb.Uri.toObject, includeInstance),
    basedOnList: jspb.Message.toObjectList(msg.getBasedOnList(),
    proto_r4_core_datatypes_pb.Reference.toObject, includeInstance),
    partOfList: jspb.Message.toObjectList(msg.getPartOfList(),
    proto_r4_core_datatypes_pb.Reference.toObject, includeInstance),
    inResponseToList: jspb.Message.toObjectList(msg.getInResponseToList(),
    proto_r4_core_datatypes_pb.Reference.toObject, includeInstance),
    status: (f = msg.getStatus()) && proto.google.fhir.r4.core.Communication.StatusCode.toObject(includeInstance, f),
    statusReason: (f = msg.getStatusReason()) && proto_r4_core_datatypes_pb.CodeableConcept.toObject(includeInstance, f),
    categoryList: jspb.Message.toObjectList(msg.getCategoryList(),
    proto_r4_core_datatypes_pb.CodeableConcept.toObject, includeInstance),
    priority: (f = msg.getPriority()) && proto.google.fhir.r4.core.Communication.PriorityCode.toObject(includeInstance, f),
    mediumList: jspb.Message.toObjectList(msg.getMediumList(),
    proto_r4_core_datatypes_pb.CodeableConcept.toObject, includeInstance),
    subject: (f = msg.getSubject()) && proto_r4_core_datatypes_pb.Reference.toObject(includeInstance, f),
    topic: (f = msg.getTopic()) && proto_r4_core_datatypes_pb.CodeableConcept.toObject(includeInstance, f),
    aboutList: jspb.Message.toObjectList(msg.getAboutList(),
    proto_r4_core_datatypes_pb.Reference.toObject, includeInstance),
    encounter: (f = msg.getEncounter()) && proto_r4_core_datatypes_pb.Reference.toObject(includeInstance, f),
    sent: (f = msg.getSent()) && proto_r4_core_datatypes_pb.DateTime.toObject(includeInstance, f),
    received: (f = msg.getReceived()) && proto_r4_core_datatypes_pb.DateTime.toObject(includeInstance, f),
    recipientList: jspb.Message.toObjectList(msg.getRecipientList(),
    proto_r4_core_datatypes_pb.Reference.toObject, includeInstance),
    sender: (f = msg.getSender()) && proto_r4_core_datatypes_pb.Reference.toObject(includeInstance, f),
    reasonCodeList: jspb.Message.toObjectList(msg.getReasonCodeList(),
    proto_r4_core_datatypes_pb.CodeableConcept.toObject, includeInstance),
    reasonReferenceList: jspb.Message.toObjectList(msg.getReasonReferenceList(),
    proto_r4_core_datatypes_pb.Reference.toObject, includeInstance),
    payloadList: jspb.Message.toObjectList(msg.getPayloadList(),
    proto.google.fhir.r4.core.Communication.Payload.toObject, includeInstance),
    noteList: jspb.Message.toObjectList(msg.getNoteList(),
    proto_r4_core_datatypes_pb.Annotation.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.fhir.r4.core.Communication}
 */
proto.google.fhir.r4.core.Communication.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.fhir.r4.core.Communication;
  return proto.google.fhir.r4.core.Communication.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.fhir.r4.core.Communication} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.fhir.r4.core.Communication}
 */
proto.google.fhir.r4.core.Communication.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto_r4_core_datatypes_pb.Id;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Id.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = new proto_r4_core_datatypes_pb.Meta;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Meta.deserializeBinaryFromReader);
      msg.setMeta(value);
      break;
    case 3:
      var value = new proto_r4_core_datatypes_pb.Uri;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Uri.deserializeBinaryFromReader);
      msg.setImplicitRules(value);
      break;
    case 4:
      var value = new proto_r4_core_datatypes_pb.Code;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Code.deserializeBinaryFromReader);
      msg.setLanguage(value);
      break;
    case 5:
      var value = new proto_r4_core_datatypes_pb.Narrative;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Narrative.deserializeBinaryFromReader);
      msg.setText(value);
      break;
    case 6:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.addContained(value);
      break;
    case 8:
      var value = new proto_r4_core_datatypes_pb.Extension;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Extension.deserializeBinaryFromReader);
      msg.addExtension$(value);
      break;
    case 9:
      var value = new proto_r4_core_datatypes_pb.Extension;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Extension.deserializeBinaryFromReader);
      msg.addModifierExtension(value);
      break;
    case 10:
      var value = new proto_r4_core_datatypes_pb.Identifier;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Identifier.deserializeBinaryFromReader);
      msg.addIdentifier(value);
      break;
    case 11:
      var value = new proto_r4_core_datatypes_pb.Canonical;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Canonical.deserializeBinaryFromReader);
      msg.addInstantiatesCanonical(value);
      break;
    case 12:
      var value = new proto_r4_core_datatypes_pb.Uri;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Uri.deserializeBinaryFromReader);
      msg.addInstantiatesUri(value);
      break;
    case 13:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.addBasedOn(value);
      break;
    case 14:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.addPartOf(value);
      break;
    case 15:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.addInResponseTo(value);
      break;
    case 16:
      var value = new proto.google.fhir.r4.core.Communication.StatusCode;
      reader.readMessage(value,proto.google.fhir.r4.core.Communication.StatusCode.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 17:
      var value = new proto_r4_core_datatypes_pb.CodeableConcept;
      reader.readMessage(value,proto_r4_core_datatypes_pb.CodeableConcept.deserializeBinaryFromReader);
      msg.setStatusReason(value);
      break;
    case 18:
      var value = new proto_r4_core_datatypes_pb.CodeableConcept;
      reader.readMessage(value,proto_r4_core_datatypes_pb.CodeableConcept.deserializeBinaryFromReader);
      msg.addCategory(value);
      break;
    case 19:
      var value = new proto.google.fhir.r4.core.Communication.PriorityCode;
      reader.readMessage(value,proto.google.fhir.r4.core.Communication.PriorityCode.deserializeBinaryFromReader);
      msg.setPriority(value);
      break;
    case 20:
      var value = new proto_r4_core_datatypes_pb.CodeableConcept;
      reader.readMessage(value,proto_r4_core_datatypes_pb.CodeableConcept.deserializeBinaryFromReader);
      msg.addMedium(value);
      break;
    case 21:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.setSubject(value);
      break;
    case 22:
      var value = new proto_r4_core_datatypes_pb.CodeableConcept;
      reader.readMessage(value,proto_r4_core_datatypes_pb.CodeableConcept.deserializeBinaryFromReader);
      msg.setTopic(value);
      break;
    case 23:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.addAbout(value);
      break;
    case 24:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.setEncounter(value);
      break;
    case 25:
      var value = new proto_r4_core_datatypes_pb.DateTime;
      reader.readMessage(value,proto_r4_core_datatypes_pb.DateTime.deserializeBinaryFromReader);
      msg.setSent(value);
      break;
    case 26:
      var value = new proto_r4_core_datatypes_pb.DateTime;
      reader.readMessage(value,proto_r4_core_datatypes_pb.DateTime.deserializeBinaryFromReader);
      msg.setReceived(value);
      break;
    case 27:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.addRecipient(value);
      break;
    case 28:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.setSender(value);
      break;
    case 29:
      var value = new proto_r4_core_datatypes_pb.CodeableConcept;
      reader.readMessage(value,proto_r4_core_datatypes_pb.CodeableConcept.deserializeBinaryFromReader);
      msg.addReasonCode(value);
      break;
    case 30:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.addReasonReference(value);
      break;
    case 31:
      var value = new proto.google.fhir.r4.core.Communication.Payload;
      reader.readMessage(value,proto.google.fhir.r4.core.Communication.Payload.deserializeBinaryFromReader);
      msg.addPayload(value);
      break;
    case 32:
      var value = new proto_r4_core_datatypes_pb.Annotation;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Annotation.deserializeBinaryFromReader);
      msg.addNote(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.fhir.r4.core.Communication.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.fhir.r4.core.Communication.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.fhir.r4.core.Communication} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.Communication.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto_r4_core_datatypes_pb.Id.serializeBinaryToWriter
    );
  }
  f = message.getMeta();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto_r4_core_datatypes_pb.Meta.serializeBinaryToWriter
    );
  }
  f = message.getImplicitRules();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto_r4_core_datatypes_pb.Uri.serializeBinaryToWriter
    );
  }
  f = message.getLanguage();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto_r4_core_datatypes_pb.Code.serializeBinaryToWriter
    );
  }
  f = message.getText();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto_r4_core_datatypes_pb.Narrative.serializeBinaryToWriter
    );
  }
  f = message.getContainedList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
  f = message.getExtensionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      proto_r4_core_datatypes_pb.Extension.serializeBinaryToWriter
    );
  }
  f = message.getModifierExtensionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      proto_r4_core_datatypes_pb.Extension.serializeBinaryToWriter
    );
  }
  f = message.getIdentifierList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      proto_r4_core_datatypes_pb.Identifier.serializeBinaryToWriter
    );
  }
  f = message.getInstantiatesCanonicalList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      proto_r4_core_datatypes_pb.Canonical.serializeBinaryToWriter
    );
  }
  f = message.getInstantiatesUriList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      proto_r4_core_datatypes_pb.Uri.serializeBinaryToWriter
    );
  }
  f = message.getBasedOnList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getPartOfList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      14,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getInResponseToList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      15,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      proto.google.fhir.r4.core.Communication.StatusCode.serializeBinaryToWriter
    );
  }
  f = message.getStatusReason();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      proto_r4_core_datatypes_pb.CodeableConcept.serializeBinaryToWriter
    );
  }
  f = message.getCategoryList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      18,
      f,
      proto_r4_core_datatypes_pb.CodeableConcept.serializeBinaryToWriter
    );
  }
  f = message.getPriority();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      proto.google.fhir.r4.core.Communication.PriorityCode.serializeBinaryToWriter
    );
  }
  f = message.getMediumList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      20,
      f,
      proto_r4_core_datatypes_pb.CodeableConcept.serializeBinaryToWriter
    );
  }
  f = message.getSubject();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getTopic();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      proto_r4_core_datatypes_pb.CodeableConcept.serializeBinaryToWriter
    );
  }
  f = message.getAboutList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      23,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getEncounter();
  if (f != null) {
    writer.writeMessage(
      24,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getSent();
  if (f != null) {
    writer.writeMessage(
      25,
      f,
      proto_r4_core_datatypes_pb.DateTime.serializeBinaryToWriter
    );
  }
  f = message.getReceived();
  if (f != null) {
    writer.writeMessage(
      26,
      f,
      proto_r4_core_datatypes_pb.DateTime.serializeBinaryToWriter
    );
  }
  f = message.getRecipientList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      27,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getSender();
  if (f != null) {
    writer.writeMessage(
      28,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getReasonCodeList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      29,
      f,
      proto_r4_core_datatypes_pb.CodeableConcept.serializeBinaryToWriter
    );
  }
  f = message.getReasonReferenceList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      30,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
  f = message.getPayloadList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      31,
      f,
      proto.google.fhir.r4.core.Communication.Payload.serializeBinaryToWriter
    );
  }
  f = message.getNoteList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      32,
      f,
      proto_r4_core_datatypes_pb.Annotation.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.fhir.r4.core.Communication.StatusCode.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.fhir.r4.core.Communication.StatusCode.prototype.toObject = function(opt_includeInstance) {
  return proto.google.fhir.r4.core.Communication.StatusCode.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.fhir.r4.core.Communication.StatusCode} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.Communication.StatusCode.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: jspb.Message.getFieldWithDefault(msg, 1, 0),
    id: (f = msg.getId()) && proto_r4_core_datatypes_pb.String.toObject(includeInstance, f),
    extensionList: jspb.Message.toObjectList(msg.getExtensionList(),
    proto_r4_core_datatypes_pb.Extension.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.fhir.r4.core.Communication.StatusCode}
 */
proto.google.fhir.r4.core.Communication.StatusCode.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.fhir.r4.core.Communication.StatusCode;
  return proto.google.fhir.r4.core.Communication.StatusCode.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.fhir.r4.core.Communication.StatusCode} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.fhir.r4.core.Communication.StatusCode}
 */
proto.google.fhir.r4.core.Communication.StatusCode.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.google.fhir.r4.core.EventStatusCode.Value} */ (reader.readEnum());
      msg.setValue(value);
      break;
    case 2:
      var value = new proto_r4_core_datatypes_pb.String;
      reader.readMessage(value,proto_r4_core_datatypes_pb.String.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 3:
      var value = new proto_r4_core_datatypes_pb.Extension;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Extension.deserializeBinaryFromReader);
      msg.addExtension$(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.fhir.r4.core.Communication.StatusCode.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.fhir.r4.core.Communication.StatusCode.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.fhir.r4.core.Communication.StatusCode} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.Communication.StatusCode.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValue();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto_r4_core_datatypes_pb.String.serializeBinaryToWriter
    );
  }
  f = message.getExtensionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto_r4_core_datatypes_pb.Extension.serializeBinaryToWriter
    );
  }
};


/**
 * optional EventStatusCode.Value value = 1;
 * @return {!proto.google.fhir.r4.core.EventStatusCode.Value}
 */
proto.google.fhir.r4.core.Communication.StatusCode.prototype.getValue = function() {
  return /** @type {!proto.google.fhir.r4.core.EventStatusCode.Value} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.google.fhir.r4.core.EventStatusCode.Value} value
 * @return {!proto.google.fhir.r4.core.Communication.StatusCode} returns this
 */
proto.google.fhir.r4.core.Communication.StatusCode.prototype.setValue = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional String id = 2;
 * @return {?proto.google.fhir.r4.core.String}
 */
proto.google.fhir.r4.core.Communication.StatusCode.prototype.getId = function() {
  return /** @type{?proto.google.fhir.r4.core.String} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.String, 2));
};


/**
 * @param {?proto.google.fhir.r4.core.String|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication.StatusCode} returns this
*/
proto.google.fhir.r4.core.Communication.StatusCode.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication.StatusCode} returns this
 */
proto.google.fhir.r4.core.Communication.StatusCode.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.StatusCode.prototype.hasId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated Extension extension = 3;
 * @return {!Array<!proto.google.fhir.r4.core.Extension>}
 */
proto.google.fhir.r4.core.Communication.StatusCode.prototype.getExtensionList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Extension>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Extension, 3));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Extension>} value
 * @return {!proto.google.fhir.r4.core.Communication.StatusCode} returns this
*/
proto.google.fhir.r4.core.Communication.StatusCode.prototype.setExtensionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Extension=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Extension}
 */
proto.google.fhir.r4.core.Communication.StatusCode.prototype.addExtension$ = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.google.fhir.r4.core.Extension, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication.StatusCode} returns this
 */
proto.google.fhir.r4.core.Communication.StatusCode.prototype.clearExtensionList = function() {
  return this.setExtensionList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.fhir.r4.core.Communication.PriorityCode.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.fhir.r4.core.Communication.PriorityCode.prototype.toObject = function(opt_includeInstance) {
  return proto.google.fhir.r4.core.Communication.PriorityCode.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.fhir.r4.core.Communication.PriorityCode} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.Communication.PriorityCode.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: jspb.Message.getFieldWithDefault(msg, 1, 0),
    id: (f = msg.getId()) && proto_r4_core_datatypes_pb.String.toObject(includeInstance, f),
    extensionList: jspb.Message.toObjectList(msg.getExtensionList(),
    proto_r4_core_datatypes_pb.Extension.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.fhir.r4.core.Communication.PriorityCode}
 */
proto.google.fhir.r4.core.Communication.PriorityCode.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.fhir.r4.core.Communication.PriorityCode;
  return proto.google.fhir.r4.core.Communication.PriorityCode.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.fhir.r4.core.Communication.PriorityCode} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.fhir.r4.core.Communication.PriorityCode}
 */
proto.google.fhir.r4.core.Communication.PriorityCode.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.google.fhir.r4.core.RequestPriorityCode.Value} */ (reader.readEnum());
      msg.setValue(value);
      break;
    case 2:
      var value = new proto_r4_core_datatypes_pb.String;
      reader.readMessage(value,proto_r4_core_datatypes_pb.String.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 3:
      var value = new proto_r4_core_datatypes_pb.Extension;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Extension.deserializeBinaryFromReader);
      msg.addExtension$(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.fhir.r4.core.Communication.PriorityCode.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.fhir.r4.core.Communication.PriorityCode.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.fhir.r4.core.Communication.PriorityCode} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.Communication.PriorityCode.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValue();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto_r4_core_datatypes_pb.String.serializeBinaryToWriter
    );
  }
  f = message.getExtensionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto_r4_core_datatypes_pb.Extension.serializeBinaryToWriter
    );
  }
};


/**
 * optional RequestPriorityCode.Value value = 1;
 * @return {!proto.google.fhir.r4.core.RequestPriorityCode.Value}
 */
proto.google.fhir.r4.core.Communication.PriorityCode.prototype.getValue = function() {
  return /** @type {!proto.google.fhir.r4.core.RequestPriorityCode.Value} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.google.fhir.r4.core.RequestPriorityCode.Value} value
 * @return {!proto.google.fhir.r4.core.Communication.PriorityCode} returns this
 */
proto.google.fhir.r4.core.Communication.PriorityCode.prototype.setValue = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional String id = 2;
 * @return {?proto.google.fhir.r4.core.String}
 */
proto.google.fhir.r4.core.Communication.PriorityCode.prototype.getId = function() {
  return /** @type{?proto.google.fhir.r4.core.String} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.String, 2));
};


/**
 * @param {?proto.google.fhir.r4.core.String|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication.PriorityCode} returns this
*/
proto.google.fhir.r4.core.Communication.PriorityCode.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication.PriorityCode} returns this
 */
proto.google.fhir.r4.core.Communication.PriorityCode.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.PriorityCode.prototype.hasId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated Extension extension = 3;
 * @return {!Array<!proto.google.fhir.r4.core.Extension>}
 */
proto.google.fhir.r4.core.Communication.PriorityCode.prototype.getExtensionList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Extension>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Extension, 3));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Extension>} value
 * @return {!proto.google.fhir.r4.core.Communication.PriorityCode} returns this
*/
proto.google.fhir.r4.core.Communication.PriorityCode.prototype.setExtensionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Extension=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Extension}
 */
proto.google.fhir.r4.core.Communication.PriorityCode.prototype.addExtension$ = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.google.fhir.r4.core.Extension, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication.PriorityCode} returns this
 */
proto.google.fhir.r4.core.Communication.PriorityCode.prototype.clearExtensionList = function() {
  return this.setExtensionList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.fhir.r4.core.Communication.Payload.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.fhir.r4.core.Communication.Payload.prototype.toObject = function(opt_includeInstance) {
  return proto.google.fhir.r4.core.Communication.Payload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.fhir.r4.core.Communication.Payload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.Communication.Payload.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && proto_r4_core_datatypes_pb.String.toObject(includeInstance, f),
    extensionList: jspb.Message.toObjectList(msg.getExtensionList(),
    proto_r4_core_datatypes_pb.Extension.toObject, includeInstance),
    modifierExtensionList: jspb.Message.toObjectList(msg.getModifierExtensionList(),
    proto_r4_core_datatypes_pb.Extension.toObject, includeInstance),
    content: (f = msg.getContent()) && proto.google.fhir.r4.core.Communication.Payload.ContentX.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.fhir.r4.core.Communication.Payload}
 */
proto.google.fhir.r4.core.Communication.Payload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.fhir.r4.core.Communication.Payload;
  return proto.google.fhir.r4.core.Communication.Payload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.fhir.r4.core.Communication.Payload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.fhir.r4.core.Communication.Payload}
 */
proto.google.fhir.r4.core.Communication.Payload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto_r4_core_datatypes_pb.String;
      reader.readMessage(value,proto_r4_core_datatypes_pb.String.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = new proto_r4_core_datatypes_pb.Extension;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Extension.deserializeBinaryFromReader);
      msg.addExtension$(value);
      break;
    case 3:
      var value = new proto_r4_core_datatypes_pb.Extension;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Extension.deserializeBinaryFromReader);
      msg.addModifierExtension(value);
      break;
    case 4:
      var value = new proto.google.fhir.r4.core.Communication.Payload.ContentX;
      reader.readMessage(value,proto.google.fhir.r4.core.Communication.Payload.ContentX.deserializeBinaryFromReader);
      msg.setContent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.fhir.r4.core.Communication.Payload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.fhir.r4.core.Communication.Payload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.fhir.r4.core.Communication.Payload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.Communication.Payload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto_r4_core_datatypes_pb.String.serializeBinaryToWriter
    );
  }
  f = message.getExtensionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto_r4_core_datatypes_pb.Extension.serializeBinaryToWriter
    );
  }
  f = message.getModifierExtensionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto_r4_core_datatypes_pb.Extension.serializeBinaryToWriter
    );
  }
  f = message.getContent();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.google.fhir.r4.core.Communication.Payload.ContentX.serializeBinaryToWriter
    );
  }
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX.ChoiceCase = {
  CHOICE_NOT_SET: 0,
  STRING_VALUE: 1,
  ATTACHMENT: 2,
  REFERENCE: 3
};

/**
 * @return {proto.google.fhir.r4.core.Communication.Payload.ContentX.ChoiceCase}
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX.prototype.getChoiceCase = function() {
  return /** @type {proto.google.fhir.r4.core.Communication.Payload.ContentX.ChoiceCase} */(jspb.Message.computeOneofCase(this, proto.google.fhir.r4.core.Communication.Payload.ContentX.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX.prototype.toObject = function(opt_includeInstance) {
  return proto.google.fhir.r4.core.Communication.Payload.ContentX.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.fhir.r4.core.Communication.Payload.ContentX} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX.toObject = function(includeInstance, msg) {
  var f, obj = {
    stringValue: (f = msg.getStringValue()) && proto_r4_core_datatypes_pb.String.toObject(includeInstance, f),
    attachment: (f = msg.getAttachment()) && proto_r4_core_datatypes_pb.Attachment.toObject(includeInstance, f),
    reference: (f = msg.getReference()) && proto_r4_core_datatypes_pb.Reference.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.fhir.r4.core.Communication.Payload.ContentX}
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.fhir.r4.core.Communication.Payload.ContentX;
  return proto.google.fhir.r4.core.Communication.Payload.ContentX.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.fhir.r4.core.Communication.Payload.ContentX} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.fhir.r4.core.Communication.Payload.ContentX}
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto_r4_core_datatypes_pb.String;
      reader.readMessage(value,proto_r4_core_datatypes_pb.String.deserializeBinaryFromReader);
      msg.setStringValue(value);
      break;
    case 2:
      var value = new proto_r4_core_datatypes_pb.Attachment;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Attachment.deserializeBinaryFromReader);
      msg.setAttachment(value);
      break;
    case 3:
      var value = new proto_r4_core_datatypes_pb.Reference;
      reader.readMessage(value,proto_r4_core_datatypes_pb.Reference.deserializeBinaryFromReader);
      msg.setReference(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.fhir.r4.core.Communication.Payload.ContentX.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.fhir.r4.core.Communication.Payload.ContentX} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStringValue();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto_r4_core_datatypes_pb.String.serializeBinaryToWriter
    );
  }
  f = message.getAttachment();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto_r4_core_datatypes_pb.Attachment.serializeBinaryToWriter
    );
  }
  f = message.getReference();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto_r4_core_datatypes_pb.Reference.serializeBinaryToWriter
    );
  }
};


/**
 * optional String string_value = 1;
 * @return {?proto.google.fhir.r4.core.String}
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX.prototype.getStringValue = function() {
  return /** @type{?proto.google.fhir.r4.core.String} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.String, 1));
};


/**
 * @param {?proto.google.fhir.r4.core.String|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication.Payload.ContentX} returns this
*/
proto.google.fhir.r4.core.Communication.Payload.ContentX.prototype.setStringValue = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.google.fhir.r4.core.Communication.Payload.ContentX.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication.Payload.ContentX} returns this
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX.prototype.clearStringValue = function() {
  return this.setStringValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX.prototype.hasStringValue = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Attachment attachment = 2;
 * @return {?proto.google.fhir.r4.core.Attachment}
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX.prototype.getAttachment = function() {
  return /** @type{?proto.google.fhir.r4.core.Attachment} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Attachment, 2));
};


/**
 * @param {?proto.google.fhir.r4.core.Attachment|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication.Payload.ContentX} returns this
*/
proto.google.fhir.r4.core.Communication.Payload.ContentX.prototype.setAttachment = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.google.fhir.r4.core.Communication.Payload.ContentX.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication.Payload.ContentX} returns this
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX.prototype.clearAttachment = function() {
  return this.setAttachment(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX.prototype.hasAttachment = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Reference reference = 3;
 * @return {?proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX.prototype.getReference = function() {
  return /** @type{?proto.google.fhir.r4.core.Reference} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Reference, 3));
};


/**
 * @param {?proto.google.fhir.r4.core.Reference|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication.Payload.ContentX} returns this
*/
proto.google.fhir.r4.core.Communication.Payload.ContentX.prototype.setReference = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.google.fhir.r4.core.Communication.Payload.ContentX.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication.Payload.ContentX} returns this
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX.prototype.clearReference = function() {
  return this.setReference(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.Payload.ContentX.prototype.hasReference = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional String id = 1;
 * @return {?proto.google.fhir.r4.core.String}
 */
proto.google.fhir.r4.core.Communication.Payload.prototype.getId = function() {
  return /** @type{?proto.google.fhir.r4.core.String} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.String, 1));
};


/**
 * @param {?proto.google.fhir.r4.core.String|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication.Payload} returns this
*/
proto.google.fhir.r4.core.Communication.Payload.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication.Payload} returns this
 */
proto.google.fhir.r4.core.Communication.Payload.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.Payload.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Extension extension = 2;
 * @return {!Array<!proto.google.fhir.r4.core.Extension>}
 */
proto.google.fhir.r4.core.Communication.Payload.prototype.getExtensionList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Extension>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Extension, 2));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Extension>} value
 * @return {!proto.google.fhir.r4.core.Communication.Payload} returns this
*/
proto.google.fhir.r4.core.Communication.Payload.prototype.setExtensionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Extension=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Extension}
 */
proto.google.fhir.r4.core.Communication.Payload.prototype.addExtension$ = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.google.fhir.r4.core.Extension, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication.Payload} returns this
 */
proto.google.fhir.r4.core.Communication.Payload.prototype.clearExtensionList = function() {
  return this.setExtensionList([]);
};


/**
 * repeated Extension modifier_extension = 3;
 * @return {!Array<!proto.google.fhir.r4.core.Extension>}
 */
proto.google.fhir.r4.core.Communication.Payload.prototype.getModifierExtensionList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Extension>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Extension, 3));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Extension>} value
 * @return {!proto.google.fhir.r4.core.Communication.Payload} returns this
*/
proto.google.fhir.r4.core.Communication.Payload.prototype.setModifierExtensionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Extension=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Extension}
 */
proto.google.fhir.r4.core.Communication.Payload.prototype.addModifierExtension = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.google.fhir.r4.core.Extension, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication.Payload} returns this
 */
proto.google.fhir.r4.core.Communication.Payload.prototype.clearModifierExtensionList = function() {
  return this.setModifierExtensionList([]);
};


/**
 * optional ContentX content = 4;
 * @return {?proto.google.fhir.r4.core.Communication.Payload.ContentX}
 */
proto.google.fhir.r4.core.Communication.Payload.prototype.getContent = function() {
  return /** @type{?proto.google.fhir.r4.core.Communication.Payload.ContentX} */ (
    jspb.Message.getWrapperField(this, proto.google.fhir.r4.core.Communication.Payload.ContentX, 4));
};


/**
 * @param {?proto.google.fhir.r4.core.Communication.Payload.ContentX|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication.Payload} returns this
*/
proto.google.fhir.r4.core.Communication.Payload.prototype.setContent = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication.Payload} returns this
 */
proto.google.fhir.r4.core.Communication.Payload.prototype.clearContent = function() {
  return this.setContent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.Payload.prototype.hasContent = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Id id = 1;
 * @return {?proto.google.fhir.r4.core.Id}
 */
proto.google.fhir.r4.core.Communication.prototype.getId = function() {
  return /** @type{?proto.google.fhir.r4.core.Id} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Id, 1));
};


/**
 * @param {?proto.google.fhir.r4.core.Id|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Meta meta = 2;
 * @return {?proto.google.fhir.r4.core.Meta}
 */
proto.google.fhir.r4.core.Communication.prototype.getMeta = function() {
  return /** @type{?proto.google.fhir.r4.core.Meta} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Meta, 2));
};


/**
 * @param {?proto.google.fhir.r4.core.Meta|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setMeta = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearMeta = function() {
  return this.setMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.prototype.hasMeta = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Uri implicit_rules = 3;
 * @return {?proto.google.fhir.r4.core.Uri}
 */
proto.google.fhir.r4.core.Communication.prototype.getImplicitRules = function() {
  return /** @type{?proto.google.fhir.r4.core.Uri} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Uri, 3));
};


/**
 * @param {?proto.google.fhir.r4.core.Uri|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setImplicitRules = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearImplicitRules = function() {
  return this.setImplicitRules(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.prototype.hasImplicitRules = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Code language = 4;
 * @return {?proto.google.fhir.r4.core.Code}
 */
proto.google.fhir.r4.core.Communication.prototype.getLanguage = function() {
  return /** @type{?proto.google.fhir.r4.core.Code} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Code, 4));
};


/**
 * @param {?proto.google.fhir.r4.core.Code|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setLanguage = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearLanguage = function() {
  return this.setLanguage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.prototype.hasLanguage = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Narrative text = 5;
 * @return {?proto.google.fhir.r4.core.Narrative}
 */
proto.google.fhir.r4.core.Communication.prototype.getText = function() {
  return /** @type{?proto.google.fhir.r4.core.Narrative} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Narrative, 5));
};


/**
 * @param {?proto.google.fhir.r4.core.Narrative|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setText = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearText = function() {
  return this.setText(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.prototype.hasText = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * repeated google.protobuf.Any contained = 6;
 * @return {!Array<!proto.google.protobuf.Any>}
 */
proto.google.fhir.r4.core.Communication.prototype.getContainedList = function() {
  return /** @type{!Array<!proto.google.protobuf.Any>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_protobuf_any_pb.Any, 6));
};


/**
 * @param {!Array<!proto.google.protobuf.Any>} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setContainedList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.google.protobuf.Any=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.protobuf.Any}
 */
proto.google.fhir.r4.core.Communication.prototype.addContained = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.google.protobuf.Any, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearContainedList = function() {
  return this.setContainedList([]);
};


/**
 * repeated Extension extension = 8;
 * @return {!Array<!proto.google.fhir.r4.core.Extension>}
 */
proto.google.fhir.r4.core.Communication.prototype.getExtensionList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Extension>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Extension, 8));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Extension>} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setExtensionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Extension=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Extension}
 */
proto.google.fhir.r4.core.Communication.prototype.addExtension$ = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.google.fhir.r4.core.Extension, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearExtensionList = function() {
  return this.setExtensionList([]);
};


/**
 * repeated Extension modifier_extension = 9;
 * @return {!Array<!proto.google.fhir.r4.core.Extension>}
 */
proto.google.fhir.r4.core.Communication.prototype.getModifierExtensionList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Extension>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Extension, 9));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Extension>} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setModifierExtensionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Extension=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Extension}
 */
proto.google.fhir.r4.core.Communication.prototype.addModifierExtension = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.google.fhir.r4.core.Extension, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearModifierExtensionList = function() {
  return this.setModifierExtensionList([]);
};


/**
 * repeated Identifier identifier = 10;
 * @return {!Array<!proto.google.fhir.r4.core.Identifier>}
 */
proto.google.fhir.r4.core.Communication.prototype.getIdentifierList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Identifier>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Identifier, 10));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Identifier>} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setIdentifierList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Identifier=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Identifier}
 */
proto.google.fhir.r4.core.Communication.prototype.addIdentifier = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.google.fhir.r4.core.Identifier, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearIdentifierList = function() {
  return this.setIdentifierList([]);
};


/**
 * repeated Canonical instantiates_canonical = 11;
 * @return {!Array<!proto.google.fhir.r4.core.Canonical>}
 */
proto.google.fhir.r4.core.Communication.prototype.getInstantiatesCanonicalList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Canonical>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Canonical, 11));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Canonical>} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setInstantiatesCanonicalList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Canonical=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Canonical}
 */
proto.google.fhir.r4.core.Communication.prototype.addInstantiatesCanonical = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.google.fhir.r4.core.Canonical, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearInstantiatesCanonicalList = function() {
  return this.setInstantiatesCanonicalList([]);
};


/**
 * repeated Uri instantiates_uri = 12;
 * @return {!Array<!proto.google.fhir.r4.core.Uri>}
 */
proto.google.fhir.r4.core.Communication.prototype.getInstantiatesUriList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Uri>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Uri, 12));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Uri>} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setInstantiatesUriList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Uri=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Uri}
 */
proto.google.fhir.r4.core.Communication.prototype.addInstantiatesUri = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.google.fhir.r4.core.Uri, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearInstantiatesUriList = function() {
  return this.setInstantiatesUriList([]);
};


/**
 * repeated Reference based_on = 13;
 * @return {!Array<!proto.google.fhir.r4.core.Reference>}
 */
proto.google.fhir.r4.core.Communication.prototype.getBasedOnList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Reference>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Reference, 13));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Reference>} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setBasedOnList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Reference=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.Communication.prototype.addBasedOn = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.google.fhir.r4.core.Reference, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearBasedOnList = function() {
  return this.setBasedOnList([]);
};


/**
 * repeated Reference part_of = 14;
 * @return {!Array<!proto.google.fhir.r4.core.Reference>}
 */
proto.google.fhir.r4.core.Communication.prototype.getPartOfList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Reference>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Reference, 14));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Reference>} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setPartOfList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 14, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Reference=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.Communication.prototype.addPartOf = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 14, opt_value, proto.google.fhir.r4.core.Reference, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearPartOfList = function() {
  return this.setPartOfList([]);
};


/**
 * repeated Reference in_response_to = 15;
 * @return {!Array<!proto.google.fhir.r4.core.Reference>}
 */
proto.google.fhir.r4.core.Communication.prototype.getInResponseToList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Reference>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Reference, 15));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Reference>} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setInResponseToList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 15, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Reference=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.Communication.prototype.addInResponseTo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 15, opt_value, proto.google.fhir.r4.core.Reference, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearInResponseToList = function() {
  return this.setInResponseToList([]);
};


/**
 * optional StatusCode status = 16;
 * @return {?proto.google.fhir.r4.core.Communication.StatusCode}
 */
proto.google.fhir.r4.core.Communication.prototype.getStatus = function() {
  return /** @type{?proto.google.fhir.r4.core.Communication.StatusCode} */ (
    jspb.Message.getWrapperField(this, proto.google.fhir.r4.core.Communication.StatusCode, 16));
};


/**
 * @param {?proto.google.fhir.r4.core.Communication.StatusCode|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional CodeableConcept status_reason = 17;
 * @return {?proto.google.fhir.r4.core.CodeableConcept}
 */
proto.google.fhir.r4.core.Communication.prototype.getStatusReason = function() {
  return /** @type{?proto.google.fhir.r4.core.CodeableConcept} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.CodeableConcept, 17));
};


/**
 * @param {?proto.google.fhir.r4.core.CodeableConcept|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setStatusReason = function(value) {
  return jspb.Message.setWrapperField(this, 17, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearStatusReason = function() {
  return this.setStatusReason(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.prototype.hasStatusReason = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * repeated CodeableConcept category = 18;
 * @return {!Array<!proto.google.fhir.r4.core.CodeableConcept>}
 */
proto.google.fhir.r4.core.Communication.prototype.getCategoryList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.CodeableConcept>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.CodeableConcept, 18));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.CodeableConcept>} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setCategoryList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 18, value);
};


/**
 * @param {!proto.google.fhir.r4.core.CodeableConcept=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.CodeableConcept}
 */
proto.google.fhir.r4.core.Communication.prototype.addCategory = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 18, opt_value, proto.google.fhir.r4.core.CodeableConcept, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearCategoryList = function() {
  return this.setCategoryList([]);
};


/**
 * optional PriorityCode priority = 19;
 * @return {?proto.google.fhir.r4.core.Communication.PriorityCode}
 */
proto.google.fhir.r4.core.Communication.prototype.getPriority = function() {
  return /** @type{?proto.google.fhir.r4.core.Communication.PriorityCode} */ (
    jspb.Message.getWrapperField(this, proto.google.fhir.r4.core.Communication.PriorityCode, 19));
};


/**
 * @param {?proto.google.fhir.r4.core.Communication.PriorityCode|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setPriority = function(value) {
  return jspb.Message.setWrapperField(this, 19, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearPriority = function() {
  return this.setPriority(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.prototype.hasPriority = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * repeated CodeableConcept medium = 20;
 * @return {!Array<!proto.google.fhir.r4.core.CodeableConcept>}
 */
proto.google.fhir.r4.core.Communication.prototype.getMediumList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.CodeableConcept>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.CodeableConcept, 20));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.CodeableConcept>} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setMediumList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 20, value);
};


/**
 * @param {!proto.google.fhir.r4.core.CodeableConcept=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.CodeableConcept}
 */
proto.google.fhir.r4.core.Communication.prototype.addMedium = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 20, opt_value, proto.google.fhir.r4.core.CodeableConcept, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearMediumList = function() {
  return this.setMediumList([]);
};


/**
 * optional Reference subject = 21;
 * @return {?proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.Communication.prototype.getSubject = function() {
  return /** @type{?proto.google.fhir.r4.core.Reference} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Reference, 21));
};


/**
 * @param {?proto.google.fhir.r4.core.Reference|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setSubject = function(value) {
  return jspb.Message.setWrapperField(this, 21, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearSubject = function() {
  return this.setSubject(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.prototype.hasSubject = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional CodeableConcept topic = 22;
 * @return {?proto.google.fhir.r4.core.CodeableConcept}
 */
proto.google.fhir.r4.core.Communication.prototype.getTopic = function() {
  return /** @type{?proto.google.fhir.r4.core.CodeableConcept} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.CodeableConcept, 22));
};


/**
 * @param {?proto.google.fhir.r4.core.CodeableConcept|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setTopic = function(value) {
  return jspb.Message.setWrapperField(this, 22, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearTopic = function() {
  return this.setTopic(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.prototype.hasTopic = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * repeated Reference about = 23;
 * @return {!Array<!proto.google.fhir.r4.core.Reference>}
 */
proto.google.fhir.r4.core.Communication.prototype.getAboutList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Reference>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Reference, 23));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Reference>} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setAboutList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 23, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Reference=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.Communication.prototype.addAbout = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 23, opt_value, proto.google.fhir.r4.core.Reference, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearAboutList = function() {
  return this.setAboutList([]);
};


/**
 * optional Reference encounter = 24;
 * @return {?proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.Communication.prototype.getEncounter = function() {
  return /** @type{?proto.google.fhir.r4.core.Reference} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Reference, 24));
};


/**
 * @param {?proto.google.fhir.r4.core.Reference|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setEncounter = function(value) {
  return jspb.Message.setWrapperField(this, 24, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearEncounter = function() {
  return this.setEncounter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.prototype.hasEncounter = function() {
  return jspb.Message.getField(this, 24) != null;
};


/**
 * optional DateTime sent = 25;
 * @return {?proto.google.fhir.r4.core.DateTime}
 */
proto.google.fhir.r4.core.Communication.prototype.getSent = function() {
  return /** @type{?proto.google.fhir.r4.core.DateTime} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.DateTime, 25));
};


/**
 * @param {?proto.google.fhir.r4.core.DateTime|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setSent = function(value) {
  return jspb.Message.setWrapperField(this, 25, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearSent = function() {
  return this.setSent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.prototype.hasSent = function() {
  return jspb.Message.getField(this, 25) != null;
};


/**
 * optional DateTime received = 26;
 * @return {?proto.google.fhir.r4.core.DateTime}
 */
proto.google.fhir.r4.core.Communication.prototype.getReceived = function() {
  return /** @type{?proto.google.fhir.r4.core.DateTime} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.DateTime, 26));
};


/**
 * @param {?proto.google.fhir.r4.core.DateTime|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setReceived = function(value) {
  return jspb.Message.setWrapperField(this, 26, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearReceived = function() {
  return this.setReceived(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.prototype.hasReceived = function() {
  return jspb.Message.getField(this, 26) != null;
};


/**
 * repeated Reference recipient = 27;
 * @return {!Array<!proto.google.fhir.r4.core.Reference>}
 */
proto.google.fhir.r4.core.Communication.prototype.getRecipientList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Reference>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Reference, 27));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Reference>} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setRecipientList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 27, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Reference=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.Communication.prototype.addRecipient = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 27, opt_value, proto.google.fhir.r4.core.Reference, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearRecipientList = function() {
  return this.setRecipientList([]);
};


/**
 * optional Reference sender = 28;
 * @return {?proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.Communication.prototype.getSender = function() {
  return /** @type{?proto.google.fhir.r4.core.Reference} */ (
    jspb.Message.getWrapperField(this, proto_r4_core_datatypes_pb.Reference, 28));
};


/**
 * @param {?proto.google.fhir.r4.core.Reference|undefined} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setSender = function(value) {
  return jspb.Message.setWrapperField(this, 28, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearSender = function() {
  return this.setSender(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.fhir.r4.core.Communication.prototype.hasSender = function() {
  return jspb.Message.getField(this, 28) != null;
};


/**
 * repeated CodeableConcept reason_code = 29;
 * @return {!Array<!proto.google.fhir.r4.core.CodeableConcept>}
 */
proto.google.fhir.r4.core.Communication.prototype.getReasonCodeList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.CodeableConcept>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.CodeableConcept, 29));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.CodeableConcept>} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setReasonCodeList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 29, value);
};


/**
 * @param {!proto.google.fhir.r4.core.CodeableConcept=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.CodeableConcept}
 */
proto.google.fhir.r4.core.Communication.prototype.addReasonCode = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 29, opt_value, proto.google.fhir.r4.core.CodeableConcept, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearReasonCodeList = function() {
  return this.setReasonCodeList([]);
};


/**
 * repeated Reference reason_reference = 30;
 * @return {!Array<!proto.google.fhir.r4.core.Reference>}
 */
proto.google.fhir.r4.core.Communication.prototype.getReasonReferenceList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Reference>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Reference, 30));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Reference>} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setReasonReferenceList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 30, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Reference=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Reference}
 */
proto.google.fhir.r4.core.Communication.prototype.addReasonReference = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 30, opt_value, proto.google.fhir.r4.core.Reference, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearReasonReferenceList = function() {
  return this.setReasonReferenceList([]);
};


/**
 * repeated Payload payload = 31;
 * @return {!Array<!proto.google.fhir.r4.core.Communication.Payload>}
 */
proto.google.fhir.r4.core.Communication.prototype.getPayloadList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Communication.Payload>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.fhir.r4.core.Communication.Payload, 31));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Communication.Payload>} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setPayloadList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 31, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Communication.Payload=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Communication.Payload}
 */
proto.google.fhir.r4.core.Communication.prototype.addPayload = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 31, opt_value, proto.google.fhir.r4.core.Communication.Payload, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearPayloadList = function() {
  return this.setPayloadList([]);
};


/**
 * repeated Annotation note = 32;
 * @return {!Array<!proto.google.fhir.r4.core.Annotation>}
 */
proto.google.fhir.r4.core.Communication.prototype.getNoteList = function() {
  return /** @type{!Array<!proto.google.fhir.r4.core.Annotation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto_r4_core_datatypes_pb.Annotation, 32));
};


/**
 * @param {!Array<!proto.google.fhir.r4.core.Annotation>} value
 * @return {!proto.google.fhir.r4.core.Communication} returns this
*/
proto.google.fhir.r4.core.Communication.prototype.setNoteList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 32, value);
};


/**
 * @param {!proto.google.fhir.r4.core.Annotation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.fhir.r4.core.Annotation}
 */
proto.google.fhir.r4.core.Communication.prototype.addNote = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 32, opt_value, proto.google.fhir.r4.core.Annotation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.fhir.r4.core.Communication} returns this
 */
proto.google.fhir.r4.core.Communication.prototype.clearNoteList = function() {
  return this.setNoteList([]);
};


goog.object.extend(exports, proto.google.fhir.r4.core);
