name: youyou

on: [push]
jobs:
  lint:
    name: Lint youyou
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn insall
      - name: Run eslint
        run: eslint './src/**/*.{ts,tsx,js,jsx}'
